### ISSUE TITLE
Local report - Getting a exception System.TypeLoadException: Method 'CreateDeterministicKeyBuilder' 

### ISSUE THREAD

**Issue by bibing1988** [lkosson/reportviewercore#100]
**when creating a local report, I am getting a exception. I am very clueless how to continue**

**Stack trace:**
Microsoft.Reporting.NETCore.LocalProcessingException: An error occurred during local report processing.

 ---> Microsoft.Reporting.DefinitionInvalidException: The definition of the report 'reportpath/reportname.rdlc' is invalid. ---> Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: An unexpected error occurred in Report Processing. ---> System.TypeLoadException: Method 'CreateDeterministicKeyBuilder' in type 'Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilationOptions' from assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

   --- End of inner exception stack trace ---

   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()

   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)

   at Microsoft.Reporting.NETCore.LocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)

   at Microsoft.Reporting.NETCore.LocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)

   at Microsoft.Reporting.NETCore.Report.Render(String format)

**Comment by lkosson** [comment]
Depending on the .NET version you use, try adding in your project a reference to `Microsoft.CodeAnalysis.Common` and/or `Microsoft.CodeAnalysis.VisualBasic`. Use version `3.6.0` for .NET Core 3.1, `3.8.0` for .NET 5 and `4.0.0` for .NET 6.

**Comment by bibing1988** [comment]
The references are corrected. But still the exception exists.
 **More information about the exception is, the exception is occurring only when a parameter is added and used in the report. If I remove the parameters from the report, the rdlc is rendering fine.**

**Comment by lkosson** [comment]
Double-check those assembly versions. It seems you are using version `4.2.0` of `Microsoft.CodeAnalysis.VisualBasic` and `4.1.0` **or earlier** of `Microsoft.CodeAnalysis.Common`.

**Comment by samberk1** [comment]
It solves the issue for me. Thank @lkosson 

I think you need to add in the readme that `Microsoft.CodeAnalysis.Common` is required.

**Comment by samberk1** [comment]
Is a reference to `Microsoft.ReportViewer.Common` required with this package?

**Comment by lkosson** [comment]
You don't need to reference `Microsoft.ReportViewer.Common` directly from your project. Reference either `Microsoft.ReportViewer.NETCore` or `Microsoft.ReportViewer.WinForms`.

**Comment by samberk1** [comment]
For me, if I reference `ReportViewerCore.NETCore` but not `Microsoft.CodeAnalysis.VisualBasic` throws the above error.

**Comment by lkosson** [comment]
Can you reproduce the behavior using one of the sample projects provided in this repo?
