### ISSUE TITLE
#Error when evaluating the Generic List property of Dataset

### ISSUE THREAD

**Issue by KMalaimegam** [lkosson/reportviewercore#102]
MultipleChoiceList is List property

**Dataset** 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/110872004/184049969-713e979d-ccad-4732-b117-35ad89d091b2.png">

**Expression** 
         
<img width="493" alt="image" src="https://user-images.githubusercontent.com/110872004/184049926-b544b2c8-1f9e-4621-8c0d-152082930d6e.png">

The report generates **#Error** only for a particular field

Also added [Serializable] for the model MultipleChoiceList

**Comment by KMalaimegam** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/110872004/184049686-2929128d-2ad6-4b71-8270-3b642baf007f.png">

**Comment by lkosson** [comment]
Please provide a sample project based on `ReportViewerCore.Sample.WinForms` from this repo reproducing the behavior.

**Comment by KMalaimegam** [comment]
is it the right way to read the list object in Core?

=Fields!MultipleChoiceList.Value(0).DropdownItemText

same code working fine in .NET 4.5

**Comment by lkosson** [comment]
No idea, but if it works in original RV, it should work here too.

**Comment by g136660** [comment]
Complex expressions in Visual Basic do not work in .net core on linux
https://github.com/lkosson/reportviewercore/issues/101

**Comment by lkosson** [comment]
This issue seems unrelated to #101. As far as I can tell, custom code and expressions work mostly fine on Linux.

**Comment by KMalaimegam** [comment]
I am using windows.
 VS2022 .NET 6
