### ISSUE TITLE
Hyperlink to URL in reports is not working

### ISSUE THREAD

**Issue by mario-mantese** [lkosson/reportviewercore#104]
Hi
I put a hyperlink to a help page in all my reports. Something like: https://my.site/reportshelppages/reportname

Old reportviewer control opens Chrome on that page on click

This is not working in reportviewercore, because UseShellExecute property is set to false in .NET Core by default (see https://stackoverflow.com/a/59716904)

The fix is quite simple: change line 2338 in ReportViewer.cs from
    Process.Start(url);
to
    Process.Start(new ProcessStartInfo() { FileName = url, UseShellExecute = true });

Thanks
Mario

**Comment by lkosson** [comment]
Hello. The default value for `UseShellExecute` indeed changed in .NET Core. I have applied your proposed fix; it will be included in the next release.
