### ISSUE TITLE
Blazor Server app gets error when deployed

### ISSUE THREAD

**Issue by JoeCSolomon** [lkosson/reportviewercore#106]
I am developing a Blazor Server app and it generates reports just fine when running in VS 2022.  However, I get an error when I try the same code running in IIS on a Windows server.  The error I get is;

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ReportViewer.NETCore, Version=15.1.17.0, Culture=neutral, PublicKeyToken=null'. 
The system cannot find the file specified.

I checked the directory and Microsoft.ReportViewer.NETCore, Version=15.1.17.0 is there along with Common, DataVisulization, and ProcessingObjectModel.  Can you offer any suggestions for or solutions to this error?

Joe

**Comment by lkosson** [comment]
No idea. I guess the file isn't where it's supposed to be or perhaps it isn't referenced in `APP.deps.json` file.

**Comment by JoeCSolomon** [comment]
Yes you did have an idea.  It was missing a reference in the dep file.  Thank you!!!
