### ISSUE TITLE
Getting an error when trying to use dll in .net core web app

### ISSUE THREAD

**Issue by kganesan0108** [lkosson/reportviewercore#11]
I am getting an error "**Attempt by method 'Microsoft.Reporting.NETCore.LocalReport..ctor()' to access method 'Microsoft.ReportingServices.StandalonePreviewStore..ctor()' failed.**" when trying to create an instance of LocalReport() in my .net core 3.1 app

here is my sample (which is based of the console app)

```
  string fileDirPath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
  string rdlcFilePath = string.Format("{0}\\{1}.rdlc", fileDirPath, "Invoice");
  var fs = new FileStream(rdlcFilePath, FileMode.Open);
  LocalReport CIReport = new LocalReport(); // Getting error here
  CIReport.LoadReportDefinition(fs);

  CIReport.DataSources.Add(new ReportDataSource("DataSource1", myDataSource));

  return CIReport.Render("PDF");
```

**Comment by lkosson** [comment]
If you are compiling the project by yourself, please check if both Microsoft.ReportViewer.NETCore and Microsoft.ReportViewer.Common compiled succesfully and are both copied to your output directory. It seems that one of those subprojects didn't recompile. You might also try checking if precompiled DLLs from NuGet work with your project.

**Comment by kganesan0108** [comment]
So I  cleaned and compiled the project, it was throwing an error because it was blocking the resource file, unblocking each resource file and then rebuilding the dll's and using it in my application did the trick... thanks a lot

**Comment by cosmoKenney** [comment]
@kganesan0108 I'm getting the same error in a .net 6.0 console app that I'm migrating from framework 4.8. I've installed only ReportViewerCore.NetCore. Do I need to also install Microsoft.ReportViewer.Common? And my reports are set as "Embedded resource". Do I need to do something special with those? I've never heard of "unblocking" resources.

**Comment by cosmoKenney** [comment]
@lkosson , @kganesan0108 
I'm getting the same error in a .net 6.0 console app that I'm migrating from framework 4.8. The reports have always worked in this app. I've installed only ReportViewerCore.NetCore via NuGet. Do I need to also install Microsoft.ReportViewer.Common (by Microsoft)? And my reports are set as "Embedded resource". Do I need to do something special with those? I've never heard of "unblocking" resources.

**Comment by lkosson** [comment]
`ReportViewerCore.NetCore` package from NuGet should be enough. Verify that both `Microsoft.ReportViewer.NETCore.dll` and `Microsoft.ReportViewer.Common.dll` are in your output directory. `Microsoft.ReportViewer.Common.dll` comes from `ReportViewerCore.NetCore` package. Don't install original `Microsoft.ReportViewer.Common` package by Microsoft.

**Comment by cosmoKenney** [comment]
@lkosson this was my mistake. One of our many referenced class library projects still had the winforms report viewer control installed. Replacing that with ReportViewerCore.NetCore worked fine.
