### ISSUE TITLE
Cannot load report in wpf

### ISSUE THREAD

**Issue by luis9717** [lkosson/reportviewercore#110]
Hello everybody I'm trying to load reportviewer on an WPF application but its like the component does not contains this function, Is the a way to load an rdlc report with this component?

**Comment by lkosson** [comment]
It should be possible using `WindowsFormsHost`, as described [here](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf).
