### ISSUE TITLE
ReportItemSchemas not found in datasource options

### ISSUE THREAD

**Issue by Carryflag** [lkosson/reportviewercore#114]
Hello,

first of all, thank you very much for your work!! Moving from .NET Framework to .NET Core (and now 6, 7 and so on) and leave behind built-in reporting services has really been a *smart* move from MS!! Anyway, I'm trying to have a simple report working ad I arrived at the step of adding DTOs to report. I read other comments and replies given, so I used the snippet code you provided (again, thanks!!), created ReportItemSchemas.xsd, added to project and rebuilt everything. Now I tried to map DTOs to RDLC fields, but in New Datasource I cannot find ReportItemsSchema. When I start, it asks me to use Database or Object. I choose Object and proceed to next step. Now the only item I find in the checkbox list is one named Accessibility, but no sign of ReportItemSchemas. I also restarted VS because I thjought the issue could have been related to some up-front loaded file during project loading.

Surely I'm doing something wrong because so many others succeeded...but I have no clue on what I missed :)

Thank you in advance for your assistance!!

**Comment by lkosson** [comment]
You shouldn't need to use New Datasource wizard. Right after adding `.xsd` file to your project, it should be available in "Data source" dropdown in "Add dataset" dialogbox of the report designer.

**Comment by Carryflag** [comment]
Hi and thanks for your reply.

The dropdown list is empty for me
![immagine](https://user-images.githubusercontent.com/112697240/200809756-d2af3a9a-f962-44aa-b77b-7b43f945480f.png)

I'm starting to wonder if didn't correctly add the `.xsd` fiel to the project...but it should be according to Project Explorer
![immagine](https://user-images.githubusercontent.com/112697240/200811108-6bd25c31-d763-4c36-a91c-7a3832217e7c.png)
I created the .xsd file, copied to project folder then added existing element... :(

**Comment by lkosson** [comment]
Not that dropdown - the one above, labelled "Origine dati" on your screenshot. Adding `.xsd` via _Add Existing Item_ is enough.

**Comment by Carryflag** [comment]
Ok, i tried the above one also...but situation has not changed :( 

![immagine](https://user-images.githubusercontent.com/112697240/200831646-4107371a-3204-4895-ba24-e7d7d8ce5583.png)

If I press the "New" button it simply starts the wizard, which doesn't work.

I re-checked the `.xsd` file to see if there's some problem there, but it seems ok

I'm really sorry for all tthe trouble I'm putting you into :(

```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" id="ReportItemSchemas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ListaArticoli" nillable="true" type="ListaArticoli" />
  <xs:complexType name="ListaArticoli">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="Id" type="xs:int" />
      <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Qta" type="xs:decimal" />
      <xs:element minOccurs="0" maxOccurs="1" name="Picture" type="Image" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Image" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="MarshalByRefObject">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="1" name="Tag" />
          <xs:element minOccurs="0" maxOccurs="1" name="Palette" type="ColorPalette" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MarshalByRefObject" abstract="true" />
  <xs:complexType name="ColorPalette" />
</xs:schema>
```

**Comment by Carryflag** [comment]
...and that did the trick!!

![immagine](https://user-images.githubusercontent.com/112697240/200875798-f12a6099-23b5-411e-ae6c-4b8763fe0044.png)

Thank you very much!! I also changed in my DTO the image property from `Image Picture` to `Byte[] Picture` and created again the `.xsd` file. This time all worked without need to edit the `.xsd` file. Maybe the `Image` type was the real problem all along!!

Anyway, thank You again for your patience and support!!

Keep up the great Work! :)
