### ISSUE TITLE
Does not execute properly when using PublishSingleFile

### ISSUE THREAD

**Issue by NEEXP** [lkosson/reportviewercore#119]
Microsoft.Reporting.NETCore.LocalProcessingException: 
    An error occurred during local report processing.
    ---> Microsoft.Reporting.DefinitionInvalidException: 
    The definition of the report '' is invalid. --->
    Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: 
    An unexpected error occurred in Report Processing. 
     ---> System.InvalidOperationException: 
       error BC31519: '*****' cannot be referenced because it is not a valid assembly.
           --- End of inner exception stack trace ---
           at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()
           at Microsoft.Reporting.NETCore.LocalReport.SetParameters(IEnumerable`1 parameters)

PublishProfile:

     <TargetFramework>net7.0</TargetFramework>
     <RuntimeIdentifier>win-x64</RuntimeIdentifier>
     <PublishSingleFile>true</PublishSingleFile>

**Comment by lkosson** [comment]
Publishing as a single file won't work - see #49. When compiling a report, Roslyn (VB compiler) can't reference .NET and ReportViewer assemblies when they are merged to a single file.

**Comment by aaronhudon-tsman** [comment]
> Use [Fody-Costura](https://github.com/Fody/Costura) and set PublishSingleFile to true can be successfully executed.
> 
> CreateTemporaryAssemblies must be enabled.
> 
> FodyWeavers.xml:
> 
> ```
> <Costura CreateTemporaryAssemblies='true'/>
> ```

Do you mind expanding on this a bit more?  You're confirming this can be done successfully?
