### ISSUE TITLE
HTML Rendering

### ISSUE THREAD

**Issue by v-i-n-o-d** [lkosson/reportviewercore#12]
Hi,
Is it possible to add HTML Rendering?

**Comment by lkosson** [comment]
Unlikely at the moment. HTML renderer is a part of server-side Reporting Services, while this project aims to provide functionality of client-side ReportViewer. Porting Microsoft.ReportingServices.Rendering.HtmlRenderer from RS to RV would require a lot of effort would create incompatibilites between recompiled and official version. I'll look into it, but chances of success are very slim.

**Comment by lkosson** [comment]
It turns out was quite doable and seems to work fine after removing all the ASP.NET references and porting some common code from SSRS.

**Comment by v-i-n-o-d** [comment]
You are right. I had a look at the code. HTML rendering is available in the web forms package rather than the win forms package which you have used. There are many references the web forms classes. Removing them and a few fixes can make it work i guess.

**Comment by lkosson** [comment]
I've added HTML-related outputs based on Reporting Services code. If nothing breaks, it'll be available in next NuGet package.

**Comment by v-i-n-o-d** [comment]
The basic HTML rendering works fine and it doesn't seem to break anything. Please make it available in nuget.

**Comment by lkosson** [comment]
New NuGet package is now available.
