### ISSUE TITLE
how to resolve report viewer error in .Net6 System.AggregateException in .Net6: One or more errors occurred. (The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'NTLM'.)

### ISSUE THREAD

**Issue by Pratyush057** [lkosson/reportviewercore#120]

**Comment by lkosson** [comment]
This doesn't seem strictly related to this project. Try creating a minimal project reproducing the behavior and run it against both original ReportViewer and ReportViewerCore. If the former works and the latter fails, attach the project to this issue.

**Comment by Pratyush057** [comment]
> This doesn't seem strictly related to this project. Try creating a minimal project reproducing the behavior and run it against both original ReportViewer and ReportViewerCore. If the former works and the latter fails, attach the project to this issue.

my previous project was on .net 2.0 with angular 7 now i migrated to .net6.0 with angular 14 and im using alenjuden nuget package to get reportviewer but im not getting proper result with  AspNet Core 6.0

**Comment by roguesensei** [comment]
I seem to be experiencing a similar issue, albeit my error reads `The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Kerberos'` (full details below), although I am unsure why it's asking me to use Kerberos authentication when we are using NTLM.

For reference, I am also porting a project to .NET 6.0 (from .NET Framework 4.8). I am using the same credentials, pointing to the same server from the same environment. In both versions, the first call is the `GetParameters()` method, the original code runs as expected but I run into an error when using the new version.

This is my code thus far for the .NET 6.0 version:
```cs
ServerReport serverReport = new()
{
    ReportServerUrl = new Uri(Config.SsrsConfig.ReportServerUrl),
    ReportPath = $"{report.ReportPath}{report.ReportFilename}",
    DisplayName = report.ReportDescription
};

serverReport.ReportServerCredentials.NetworkCredentials = new NetworkCredential(
    Config.SsrsConfig.ReportServerLogin,
    Config.SsrsConfig.ReportServerPassword,
    Config.SsrsConfig.ReportServerDomain);
serverReport.ReportServerCredentials.ImpersonationUser = null;
serverReport.ReportServerCredentials.SetFormsCredentials(null, null, null, null);

var requiredParameters = serverReport.GetParameters(); // Error here
```
I have also tried setting the credentials to `CredentialCache.DefaultCredentials` but the same error is thrown. Hopefully that's enough information, let me know if you need more details.

Full error details:
```
System.ServiceModel.Security.MessageSecurityException
  HResult=0x80131500
  Message=The HTTP request is unauthorized with client authentication scheme 'Ntlm'. The authentication header received from the server was 'Kerberos'.
  Source=Microsoft.ReportViewer.NETCore
  StackTrace:
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.GetSecureMethods()
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.IsSecureMethod(String methodname)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.ProxyMethodInvocation.Execute[TReturn](RSExecutionConnection connection, ProxyMethod`1 sql16Method, ProxyMethod`1 katmaiMethod, ProxyMethod`1 yukonMethod)
   at Microsoft.Reporting.NETCore.Internal.Soap.ReportingServices2005.Execution.RSExecutionConnection.LoadReport(String Report, String HistoryID)
   at Microsoft.Reporting.NETCore.SoapReportExecutionService.LoadReport(String report, String historyId)
   at Microsoft.Reporting.NETCore.ServerReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.ServerReport.GetParameters()
   at Web_SupaTrakV5.Controllers.ReportViewController.RunReport() in C:\Users\chris\Work\Projects\Web_SupaTrakV5\Web\Controllers\ReportViewController.cs:line 57

  This exception was originally thrown at this call stack:
    [External Code]
    Web_SupaTrakV5.Controllers.ReportViewController.RunReport() in ReportViewController.cs
```

**Comment by lkosson** [comment]
You can try changing `throw ex;` to `throw;` in `GetSecureMethods` method in `RSExecutionContext` to obtain actual call stack from WCF internals where authentication negotiation fails.

Also, according to [docs](https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/wcf/kerberos-not-used-call-service), setting `protectionLevel` to `EncryptAndSign` might help when server expects Kerberos authentication. Unfortunately, I have to means to test it in my environment.
