### ISSUE TITLE
Working on Linux Based Docker Container

### ISSUE THREAD

**Issue by GhayourAli** [lkosson/reportviewercore#125]
I have been using this library to general xls and pdf reports and it seems to be working fine on my local windows machine. However, on production, we need to deploy this service on linux based docker container. Will this library work on this? If so, could anyone share some example of adding its dependencies in docker file? I am getting the below exception when I try to download the report.

![image](https://user-images.githubusercontent.com/8409801/214047677-ee5252b7-96b6-4a22-a25b-3a0c8fc1d972.png)

**Comment by lkosson** [comment]
Excel renderer requires OLE components from Windows. The only way to run it on Linux is to use Wine. See "Linux rendering workaround" section on the main page of this repo for a generic workaround that should also work in Docker.
