### ISSUE TITLE
Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: 'There is no data for the field at position N.'

### ISSUE THREAD

**Issue by hovek** [lkosson/reportviewercore#13]
Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: 'There is no data for the field at position N.'

The previous version of the report viewer in .NET Framework tolerated that, now having this constraint really does not help in porting hundreds of reports to .NET 5.0. Make it tolerable for not provided dataset fields, make a property with which we can make it tolerable for such issues.

**Comment by lkosson** [comment]
Can you post full stack trace where exactly ReportProcessingException it thrown? From my experiments, it should be caught right away in MappingDataReader.GetFieldValue and converted to report warning while producing empty value and continuing report rendering.

Perhaps you get ReportProcessingException as first-chance exception only while debugger is attached?

**Comment by hovek** [comment]
I've ignored the exception and reports are rendering.
