### ISSUE TITLE
Rdlc report is not generating in pdf in docker container

### ISSUE THREAD

**Issue by Nauman321** [lkosson/reportviewercore#131]
My application is .net core 6 based and locally when i generate the report in pdf it works fine but when i added docker container it sgenerate report for html5 but not for pdf it send exception usp10.dll not find (**Unable to load shared library 'usp10.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libusp10.dll: cannot open shared object file: No such file or directory**)something like that and i install the RUN apt-get update && apt-get install -y libgdiplus in dockerfile and manually copy the usp10.dll in container but it same exception any one help 
Regards

**Comment by tahami4444** [comment]
Yes I am also facing this issue for linux docker container

**Comment by lkosson** [comment]
PDF renderer requires Uniscribe components from Windows. The only way to run it on Linux is to use Wine. See "Linux rendering workaround" section on the main page of this repo for a generic workaround.
