### ISSUE TITLE
System.Drawing.Common is not supported on this platform 

### ISSUE THREAD

**Issue by SankarErss** [lkosson/reportviewercore#132]
" System.Drawing.Common is not supported on this platform " Error Throw While Generating Pdf on Linux Host (Debian)

Pdf Report Generation Working Fine on Window Environment but Linux Host throw the error while generating Pdf
Other Report is Working fine (Excel, Word, Html5) on Debian Host

 My Target Version .Net 6.0

**Comment by lkosson** [comment]
See "Linux rendering workaround" section in the readme.

**Comment by lkosson** [comment]
What error do you get when running via wine? Have you tried running sample app from this repo with same results?

**Comment by SankarErss** [comment]
> What error do you get when running via wine? Have you tried running sample app from this repo with same results?

While Run via Wine64 it throw below error

"start_debugger Couldn't start debugger L"winedbg --auto 43 1148" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger "

**Comment by lkosson** [comment]
I mean what error (exception) you get with the actual application.

**Comment by SankarErss** [comment]
> I mean what error (exception) you get with the actual application.

i am try to run the application using wine64 on debian host 

the command line is 
"wine64 dotnet.exe projectfolder/projectname.dll"

![image](https://user-images.githubusercontent.com/125452597/229983141-11e832ff-a6cb-4b4a-9f1d-0fdc3802848e.png)

**Comment by lkosson** [comment]
There is a trace of SEHException thrown in your screenshot. See details of this exception. Also test your Wine/dotnet installation by running some simple Hello World application.

**Comment by SankarErss** [comment]
> There is a trace of SEHException thrown in your screenshot. See details of this exception. Also test your Wine/dotnet installation by running some simple Hello World application.

ok . i will check and ping the status
