### ISSUE TITLE
Empty PDF after render using ServerReport

### ISSUE THREAD

**Issue by xFoRdeX** [lkosson/reportviewercore#134]
I'm facing an issue when I try to create a PDF from a report on a remote server. 
There is my code : 

```
ServerReport report = new ServerReport 
                    { 
                        ReportServerUrl = new Uri(StaticConst.URL_REPORT),
                        ReportPath = edition.EditModèle,
                    };
                    ReportParameterInfoCollection paramsSource = report.GetParameters();

                    List<ReportParameter> parameters = new List<ReportParameter>();

                    if (paramsSource["Ref"] != null)
                        parameters.Add(new ReportParameter("Ref", Ref));
                    

                    report.SetParameters(parameters);
                    
                    report.Refresh();
                   
                    byte[] byteViewer = report.Render("PDF");
                    string fileName = string.Format(@"C:\Users\auuuu\Desktop\Photo\test{0}.pdf", DateTime.Now.Minute);
                    FileStream file = new FileStream(fileName, FileMode.Create);
                    file.Write(byteViewer, 0, byteViewer.Length);
                    file.Close();
```

The DataSource is inside the report with a query

Did I forgot something ? 

Thank's for your help !

**Comment by lkosson** [comment]
What do you mean by "Empty PDF"? Zero-bytes-long file, or a valid PDF, but without any content?

Have you tried using the same code on .NET Framework and original Report Viewer?

**Comment by xFoRdeX** [comment]
It's a Valid PDF but withour content. 
The original Report viewer is using in an other project with VB.net and it works.

**Comment by lkosson** [comment]
You might check if type of `Ref` parameter is serializable and properly passed to your method. Other than that - no idea what could be wrong.

**Comment by xFoRdeX** [comment]
> You might check if type of `Ref` parameter is serializable and properly passed to your method. Other than that - no idea what could be wrong.

That's it ! I passed a parameter which was not defined in the report. It doesn't return an error but a PDF without content. 
Thank's for your help
