### ISSUE TITLE
error trying to instantiate the LocalReport() method

### ISSUE THREAD

**Issue by ingenieros4risk** [lkosson/reportviewercore#135]
can you help me I'm  trying to instantiate the LocalReport() but I'm getting the next error: 
![image](https://user-images.githubusercontent.com/82053334/234969954-943dc263-bc44-4846-83ac-971dbb15644b.png)
![image](https://user-images.githubusercontent.com/82053334/234970480-c6e869bf-181f-418f-a879-3b897ccdae30.png)

**Comment by lkosson** [comment]
Most likely you have a mismatch between `Microsoft.ReportViewer.NETCore` and `Microsoft.ReportViewer.Common` assembly versions. Verify your project dependencies and ensure you don't have original Microsoft's ReportViewer referenced in your project.

**Comment by ingenieros4risk** [comment]
thanks
