### ISSUE TITLE
Rendering images in HTML4.0 or HTML5

### ISSUE THREAD

**Issue by shiblydangdang** [lkosson/reportviewercore#137]
I've recently switched my render option to HTML4.0 or HTML5 and images now seem to be embedded using base64 as img src (HTML4.0) and background:url (HTML5). My problem is when this HTML is sent via email to Outlook, the images aren't rendered in the email. If I open the HTML file then it renders perfectly in the browser.

Previously, when using the HTML render type it used img src=cid:XXXX.jpg and I presume provided the images as attachments to the email. This would then render perfectly in Outlook.

Is there an option for HTML4.0 and/or HTML5 to follow the same process as the previous HTML render or is there a way I can get the new embedded images to display in Outlook?

Thanks

**Comment by lkosson** [comment]
As far as I can tell, `cid:` URLs are/were generated only when exporting to `MHTML` format. `HTML4.0` and `HTML5` renderer produce a raw HTML file, which can either reference external images or embed their content as base64 string.

**Comment by shiblydangdang** [comment]
Thanks for the info. I'm trying to run the old version of our software that used the HTML render type to see what it returns.

**Comment by shiblydangdang** [comment]
Got this all working perfectly now. Thanks for your help.
