### ISSUE TITLE
DPI Scaling preview issue 

### ISSUE THREAD

**Issue by mserioli** [lkosson/reportviewercore#138]
When use scaling, report preview is not ok. Elements overlap and are misplaced.

Export functionality is ok

Thanks in advance for your support

**Comment by lkosson** [comment]
Can you provide step-by-step description how to reproduce the problem in a winforms sample project from this repo?

**Comment by mserioli** [comment]
Still not able to reproduce it with repo project.

In orde to reproduce it on my environment, I have 2 monitors, need to set the main to 125% scale, while the second to 100% and the result is:

![image](https://user-images.githubusercontent.com/2193904/237018738-8f279db6-55dd-4005-a6e2-eca82901d50a.png)


While having both monitors to 100% scale, the result is ok

![image](https://user-images.githubusercontent.com/2193904/237019022-06892866-d3c6-4bfd-89d7-26ade7d57224.png)

I'll try to get more informations. Thanks again

**Comment by lkosson** [comment]
Check your application manifest and/or `Main` method for High-DPI-Awareness declaration.

Similar issue occurs in original Report Viewer, when application declares support for high DPI and display DPI is set to 125% or higher. Also, if I remember correctly, in original Report Viewer, you had to relog after changing DPI.
