### ISSUE TITLE
When do I need Reportviewer Core?

### ISSUE THREAD

**Issue by the42** [lkosson/reportviewercore#141]
We have a couple of .Net Framework web Applications in which we integrate SSRS. Some use Report Viewer Control of Microsoft. These application are on an upgrade path towards .Net (core).
 
I wonder where do I need the report viewer control?
* If I gather parameters in the web application, send it to SSRS and get a byte stream (Excel, PDF, ...) as a result, I do not need report viewer control, correct?
* If the application allows a degree of interaction with the report, like drill-down into a pivot, I do require reportviewer.

Is this picture correct / to simplistic?

**Comment by lkosson** [comment]
This is correct, but keep in mind there is no web report viewer control available in this project - only a WinForms one.

If you collect report parameters on our own in your application (web or desktop) and present PDF/XLSX/etc to user, you don't need report viewer control as you stated - see `ReportViewerCore.Sample.AspNetCore` project in this repo for an example.

If your existing **web** application allows users to interact with a report (sort, pivot etc), there is no way to port that behavior to .NET Core - at least not with this project.

If your existing **WinForms** application uses interactive reports, see `ReportViewerCore.Sample.WinForms` project for an example of such setup.

**Comment by the42** [comment]
Thank you for you quick reply! I admit I must have read the Readme to hastily as I was under the impression that this project would offer a solution for web based applications too. Now you gave me food for thought how to replace the current implementation with an alternative (probably PowerBI)
