### ISSUE TITLE
can use this library to Render rdlc as PDF in linux app release

### ISSUE THREAD

**Issue by tawfiqdawod** [lkosson/reportviewercore#143]
Hello,
Is there any way to render RDLC report as PDF in linux app release ?
I read about itext7 but I cannot use it to render RDLC report

**Comment by lkosson** [comment]
Yes, see "Linux rendering workaround" section in readme.

**Comment by tawfiqdawod** [comment]
I saw that, but experts prefer not use a wine in production mode, also when I tried to use I faced an issue described here:
https://stackoverflow.com/questions/76454168/run-net-core-6-application-in-ubuntu-using-wine

I am thankful for helping me

**Comment by lkosson** [comment]
As far as I can tell, there is no other way to directly produce PDF from RDLC when deploying to Linux server. You might try rendering your report to HTML and then using one of HTML-to-PDF converters, but in my opinion that is more error prone method.

**Comment by tawfiqdawod** [comment]
Is there a possibility to update library to directly render to PDF in linux in near future ?

**Comment by lkosson** [comment]
Not in the foreseeable future.

**Comment by lkosson** [comment]
See #144

**Comment by tawfiqdawod** [comment]
Linux workaround, did you mean in this section use wine for (Debian Bullseye or Bookworm),
run .net 6 app on ubuntu using wine cannot done ?
because I faced an issue for this here:
https://stackoverflow.com/questions/76454168/run-net-core-6-application-in-ubuntu-using-wine

**Comment by lkosson** [comment]
You can use whichever Linux distribution you like. Ubuntu is fine as long as you make sure to use Wine 5.0 or newer.
