### ISSUE TITLE
MethodAccessException

### ISSUE THREAD

**Issue by ng19932023** [lkosson/reportviewercore#145]
Hi,

I'm having the exception below when instantiating LocalReport.

![image](https://github.com/lkosson/reportviewercore/assets/138762943/b7ced7d9-9893-4b07-b2c1-8958a5b1ee17)

Thanks.

**Comment by lkosson** [comment]
Check your dependencies - make sure you are not referencing `Microsoft.ReportViewer.Common.dll` from Microsoft. A proper version is provided by this package and only that one should be (implicitly) referenced.

**Comment by ng19932023** [comment]
Hi,

Problem Solved.

Thanks.
