### ISSUE TITLE
Change DllImport to Vanara api

### ISSUE THREAD

**Issue by torgashov** [lkosson/reportviewercore#147]
Is it possible to change DllImport to Vanara api call?
https://github.com/dahall/Vanara
Can this remove windows platform dependency?

**Comment by lkosson** [comment]
That won't remove the dependency, just move it one layer deeper.

**Comment by torgashov** [comment]
Lkosson, is there way to use certain *.so files, used in project, from Wine, without installing Wine to the server?

**Comment by lkosson** [comment]
No idea, I haven't tried that.

**Comment by torgashov** [comment]
Miserably, i have one run to the cross platform using ...

**Comment by torgashov** [comment]
May be you know way to convert c++ to C# ?
C++ sources is accessed in wine repository: https://github.com/stefand/wine/blob/a3b0ab48b13f0bbe86a7236af05e9373d13a8d9d/dlls/usp10/usp10.c#L635
