### ISSUE TITLE
Encoding issue. Showing ? instead of Croatian characters.

### ISSUE THREAD

**Issue by hovek** [lkosson/reportviewercore#15]
Instead of ŠĐČĆŽ it shows ?. Language in the report is set to hr-HR.

**Comment by lkosson** [comment]
If this occurs in static report elements, check if the RDLC file is encoded as UTF-8. Also, try putting those characters in ReportViewerCore.Sample.WinForms project and check if it works there.

**Comment by hovek** [comment]
File has <?xml version="1.0" encoding="utf-8"?>
and when shown in a designer it shows Croatian characters. It also renders the characters with an old report viewer.

**Comment by lkosson** [comment]
If you put those characters in `Report.rdlc` in `ReportViewerCore.Sample.WinForms` project, do they render correctly?

**Comment by hovek** [comment]
> If you put those characters in `Report.rdlc` in `ReportViewerCore.Sample.WinForms` project, do they render correctly?

Those characters are in the report, they are in the static text, not from datasource.

**Comment by lkosson** [comment]
Can you reproduce this behavior in a report in `ReportViewerCore.Sample.WinForms` project or attach your RDLC here?
Also, how do you load your report? Using FileStream or in some other way?

**Comment by hovek** [comment]
> Can you reproduce this behavior in a report in `ReportViewerCore.Sample.WinForms` project or attach your RDLC here?
No, I am not using that. I am using Assembly Microsoft.ReportViewer.NETCore.

> Also, how do you load your report? Using FileStream or in some other way?
LocalReport.ReportPath = reportPath;

**Comment by hovek** [comment]
Can you reproduce this behavior in a report in ReportViewerCore.Sample.WinForms project or attach your RDLC here?

Also, how do you load your report? Using FileStream or in some other way?
LocalReport.ReportPath = reportPath;

KnjigaUraLista.zip

**Comment by lkosson** [comment]
PDF encoding for characters "ŽžŠš" was broken. I'll post a fix in a moment.

**Comment by hovek** [comment]
> PDF encoding for characters "ŽžŠš" was broken. I'll post a fix in a moment.

Ok, I accidentally closed this issue.

**Comment by hovek** [comment]
> PDF encoding for characters "ŽžŠš" was broken. I'll post a fix in a moment.

When will the next NuGet package be with these fixes?

**Comment by lkosson** [comment]
I have just uploaded them. Should be available in 30 minutes or so.

**Comment by hovek** [comment]
> I have just uploaded them. Should be available in 30 minutes or so.

Now the encoding is ok but it won't render subreport:
![image](https://user-images.githubusercontent.com/5937551/105985137-5f4cd400-609b-11eb-865e-579694290669.png)

**Comment by hovek** [comment]
> I have just uploaded them. Should be available in 30 minutes or so.

I get this errors on subreport processing on this code:
`spe.DataSources.Add(new ReportDataSource("DataSet1", Tables.First(t => t.TableName == report)));`
System.InvalidOperationException: 'Sequence contains no matching element'
