### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by waxwing** [lkosson/reportviewercore#152]
I'm getting an issue on an existing project but managed to recreate the same issue on a brand new test project. When I try to install the nuget package on a new ASP.Net MVC .NET 7.0 (then update all packages) project I get 

Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.4.0 directly to project TestScaffolding to resolve this issue. 
 TestScaffolding -> Microsoft.VisualStudio.Web.CodeGeneration.Design 7.0.9 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 7.0.9 -> Microsoft.VisualStudio.Web.CodeGeneration 7.0.9 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 7.0.9 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 7.0.9 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 7.0.9 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 7.0.9 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.4.0 -> Microsoft.CodeAnalysis.Common (= 4.4.0) 
 TestScaffolding -> ReportViewerCore.NETCore 15.1.17 -> Microsoft.CodeAnalysis.VisualBasic 4.0.0 -> Microsoft.CodeAnalysis.Common (= 4.0.0).	

I get the same issue on an existing project after upgrading all packages. I had a go at downloading the source to try and figure out which thing needs fixing but I don't have a lot of free time unfortunately. Any help would be much appreciated, thanks!

**Comment by lkosson** [comment]
I have fixed references to `Microsoft.CodeAnalysis.Common` for .NET 7 version. New packages are now available on NuGet.

**Comment by waxwing** [comment]
Thank you so much, that has made my day.
