### ISSUE TITLE
Error on instance create

### ISSUE THREAD

**Issue by joe-bernardes** [lkosson/reportviewercore#155]
Hi,
I have a error when instance create .NET Core 6.0
LocalReport report = new LocalReport()

(System.MethodAccessException: 'Attempt by method 'Microsoft.Reporting.NETCore.LocalReport..ctor()' to access method 'Microsoft.ReportingServices.StandalonePreviewStore..ctor()' failed.')

Can you help me, please.
Tks.

**Comment by lkosson** [comment]
Check if you don't have original Microsoft Report Viewer packages referenced in your project.
