### ISSUE TITLE
Nested objects support in expressions.

### ISSUE THREAD

**Issue by aprjanka** [lkosson/reportviewercore#157]
Most of my reports use nested objects in expressions.

Example: =Fields!A.Value.B

In this case the report datasource's object has a property "A" which is a complex object, and we want to display "B" property of the complex object.
This type of expressions works fine in my old .net winform project. The "only" requirement for this that the report datasource's object should be serializable.

After converting my winform app to .net 7, the nested object expressions no longer works: I got "#Error" displayed in the rendered report for this type of expressions. (The report datasource object are still fully serializable in .net 7)

**Comment by lkosson** [comment]
`BinaryFormatter` is obsolete since .NET 5, is disabled since .NET 6 and will be completely removed in .NET 8.
