### ISSUE TITLE
PDF Pagination on the UI

### ISSUE THREAD

**Issue by Olimarrex** [lkosson/reportviewercore#159]
https://github.com/lkosson/reportviewercore/issues/35 mentions paginating via use of deviceInfo for sections. But this option seems to be ignored for PDFs. Is there any way to render a single page or do you have to render the entire report, or render the report as HTML5?

**Comment by lkosson** [comment]
In this regard everything should work the same as in original ReportViewer.

**Comment by Olimarrex** [comment]
Didn't know there was an original ReportViewer - where do I find the info on that?

**Comment by lkosson** [comment]
https://learn.microsoft.com/en-us/sql/reporting-services/ would be a good start, https://learn.microsoft.com/en-us/sql/reporting-services/pdf-device-information-settings to be more specific.

**Comment by sraban75** [comment]
@Olimarrex  did you mean this? 

![image](https://github.com/lkosson/reportviewercore/assets/14300279/3df54724-25fd-49e5-a51b-2c187e2138a3)

**Comment by Olimarrex** [comment]
> @Olimarrex did you mean this?

I meant retrieving the page count as an integer for use elsewhere.

**Comment by sraban75** [comment]
You can use RDLC default Pagination Code.
=Globals!PageNumber
=Globals!TotalPages

**Comment by Olimarrex** [comment]
Ok, thanks. I'll see if I can use that next time I come across this issue.
