### ISSUE TITLE
Problem repeating column header for each pages

### ISSUE THREAD

**Issue by An3rAndr0s** [lkosson/reportviewercore#161]
Hi, I was unable to repeat column headers on each pages. Do you know some issue about this ?

I have a report made for a .NetFramework 4.8 WinForms app and working. Now I have ported the report in a .NetCore with WinForms and doesn't work.

I tried to rebuild the table from scratch. Usually, to active column header repeating, is necessary only active the check box in the tablix configuration. But nothing working.

**Comment by lkosson** [comment]
Can you reproduce the behavior using `ReportViewerCore.Sample.WinForms` project in this repo?

**Comment by An3rAndr0s** [comment]
I Lukasz, In ReportViewerCore.Sample.WinForms project I have added some ReportItems in Report.cs to add many rows to the report. In Report.rdlc by Design tool I have set "RepeatColumnHeaders" & "FixedColumnHeaders" to true. But the result is a 2 pages report where in the second page ColumnsHeaders are not present.
[update.zip](https://github.com/lkosson/reportviewercore/files/13437309/update.zip)
![image](https://github.com/lkosson/reportviewercore/assets/91410547/8e79baa4-7a69-4f62-9558-fa4a21920474)

**Comment by lkosson** [comment]
I see. Indeed it is broken, while I'm 100% sure it worked correctly about one year ago.

**Comment by lkosson** [comment]
Now I get same behavior (missing column headers on subsequent pages) when using original Report Viewer on .NET Framework 4.7.2. I begin to question my own sanity.

**Comment by lkosson** [comment]
Set it here and it will work:

![img](https://github.com/lkosson/reportviewercore/assets/22995707/03fa6680-3522-4ec2-940a-914979b623ec)

**Comment by An3rAndr0s** [comment]
Hi Lukas, is so strange. I had checked and tested every advanced settings of Row and Column Groups moving the RepeatOnNewPage flags yet, but always with the same problem in the report.
Now I have rebuild from scratch the tablix, changed the setting in the config page of tablix and enable "RepeatOnNewPage" in the advanced configuration of row groups and problem is disappeared.

Thanks for the support, please excuse me for time loosed for help me.
