### ISSUE TITLE
Export to Excel, PDF, etc (Except HTML5) is error on 2nd call

### ISSUE THREAD

**Issue by chandra-arifin** [lkosson/reportviewercore#163]
i have winforms with report viewer (4 parameters at the rdlc report),  then i export (use button built in).
for the 1st time, the export will be fine. but after that, error occurred. i must close the apps and launch again, but error still there. how to solved this? if i don't have parameters on the rdlc report, this problems not exists.

the code is:
using var frmRpt_PrintPD = new FrmRpt_PrintPD(@"Maintenance\rptPrintPermintaanImport.rdlc");
frmRpt_PrintPD.ShowDialog();

if i use one form, the problem not appears.

This exception was originally thrown at this call stack:
    System.Drawing.Image.Save(System.IO.Stream, System.Drawing.Imaging.ImageCodecInfo, System.Drawing.Imaging.EncoderParameters)
    System.Drawing.Image.Save(System.IO.Stream, System.Drawing.Imaging.ImageFormat)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.GetInvalidImage(Microsoft.ReportingServices.Rendering.ExcelRenderer.Excel.IExcelGenerator, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.ImageInformation>, ref bool)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderImage(Microsoft.ReportingServices.Rendering.ExcelRenderer.Excel.IExcelGenerator, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.ImageInformation>, Microsoft.ReportingServices.Rendering.RPLProcessing.RPLElementProps, int, int, int, int, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.IRowItemStruct)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderNewItem(Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.IRowItemStruct, int, int, Microsoft.ReportingServices.Rendering.ExcelRenderer.Excel.IExcelGenerator, string, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.BorderInfo>, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.ImageInformation>, ref bool, ref bool)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.LayoutEngine.RenderPageToExcel(Microsoft.ReportingServices.Rendering.ExcelRenderer.Excel.IExcelGenerator, string, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.BorderInfo>, System.Collections.Generic.Dictionary<string, Microsoft.ReportingServices.Rendering.ExcelRenderer.Layout.ImageInformation>)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.MainEngine.RenderRPLPage(Microsoft.ReportingServices.Rendering.RPLProcessing.RPLReport, bool, bool)
    Microsoft.ReportingServices.Rendering.ExcelRenderer.ExcelRenderer.Render(Microsoft.ReportingServices.OnDemandReportRendering.Report, System.Collections.Specialized.NameValueCollection, System.Collections.Specialized.NameValueCollection, System.Collections.Specialized.NameValueCollection, ref System.Collections.Hashtable, Microsoft.ReportingServices.Interfaces.CreateAndRegisterStream)

**Comment by lkosson** [comment]
This is indeed a bug in RVC, introduced in #53. The fix is ready and will be included in next release. For a workaround, check your report for invalid images - the bug only manifests when report references images which can not be loaded and are shown as a placeholder like this: 
![obraz](https://github.com/lkosson/reportviewercore/assets/22995707/e5d1a471-81c1-47fd-b58a-5fe0b0f78466)
