### ISSUE TITLE
Support for WebForms ReportViewer?

### ISSUE THREAD

**Issue by milkmanmatty** [lkosson/reportviewercore#164]
This library looks amazing, does it cover using `Microsoft.Reporting.WebForms.ReportViewer`? or is that out of scope? I don't see it mentioned anywhere.

**Comment by lkosson** [comment]
Neither supported or planned, as mentioned in last paragraph off `How to use` in readme. Web UI of ReportViewer relies heavily on ASP.NET pipeline, which is completely missing in .NET Core. In principle it is possible to rewrite it as a Razor Page or client-size application, but the amount of work is far beyond what I can spend right now.

Closest thing you can get using this project is rendering your report to static HTML and showing that in an iframe in your application - there are `HTML5` and obsolete `HTML4.0` renderers for that, grafted from Reporting Services server.

**Comment by milkmanmatty** [comment]
Oh I missed that! thanks for the info.
