### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by RudyWangCodes** [lkosson/reportviewercore#165]
Hello,

i got an error when using .NET 8

conflict Microsoft.CodeAnalysis.Common

is anyone have this error?

**Comment by RudyWangCodes** [comment]
Hello,

i think because of this
![image](https://github.com/lkosson/reportviewercore/assets/32007313/2a68f0e0-2759-434c-a393-c3ab0b695ecf)

if i include the prelease direct to my csproj with the same version of Microsoft.CodeAnalysis.VisualBasic that used in  Microsoft.ReportViewer.Common, it's work
![image](https://github.com/lkosson/reportviewercore/assets/32007313/c07fdf27-93c2-47e6-9e8f-b9a2df55abc8)

**Comment by lkosson** [comment]
See #160 and #162
