### ISSUE TITLE
Facing Microsoft.CodeAnalysis.Common issue

### ISSUE THREAD

**Issue by sraban75** [lkosson/reportviewercore#166]
Hello devs, I hope everybody is doing well. I have been using this library for 2020. It is working fine, except for slowness.
I am wondering, in the near future, is RDLC can survive? because MS doesn't support this natively in the net core, and there is no free alternative of RDLC.

Today I upgraded my application from net 7 to net 8 and upgraded report viewer 15.17 to 15.19, now I am facing this issue.
can you please tell me why this happening? 

![Screenshot_1](https://github.com/lkosson/reportviewercore/assets/14300279/3c0913b7-3968-4573-9409-f45762d13134)

**Comment by lkosson** [comment]
Try updating the package that requires version 4.5.0 of `Microsoft.CodeAnalysis.*` to one which depends on version 4.8.0.

**Comment by sraban75** [comment]
The problem was solved after installing these two packages.

![image](https://github.com/lkosson/reportviewercore/assets/14300279/a77bf1a4-e200-46dc-a701-0b6f6ab856cf)
