### ISSUE TITLE
Large file rendering issue

### ISSUE THREAD

**Issue by sraban75** [lkosson/reportviewercore#169]
Dear Ikosson, hope you are doing well, I am very much grateful to you for this library,
I am facing an issue from the beginning of this library, 
Problem: Sometimes I need to render large files, such as 2k+ pages PDF files, and need to generate both .pdf and .xlsx format
so I can see, that when the pdf file is too large, first of all, it takes more time to generate the .rdlc and the file size will be more than 100+mb, 
so the client has to wait until it is fully loaded, for network slowness, a 100MB file needs more than 5-10 mins to load.

Expectation: now, what I need, 
1- If it is possible to generate the .rdlc file based on pagination, 
2- if it is possible for the streaming system, the backend returns by a chunk of pages.

please give me some suggestions on how can I solve my problem. 
btw: my tech is: .net core 8.0 and Angular 17

Thanks in advance
and Happy New Year

**Comment by lkosson** [comment]
Rendering only specific page range with this library should work the same as in original ReportViewer / Reporting Services. See #35 and perhaps https://learn.microsoft.com/en-us/sql/reporting-services/pdf-device-information-settings
