### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by hovek** [lkosson/reportviewercore#17]
I've rendered completely the same report in .NET Framework ReportViewer and with reportviewercore.
In core it adds extra zeros in decimal and spaces in dates. Format string in rdlc in fields with three decimal places is "N". This could be an issue with .NET 5.0.

.NET Framework:
![image](https://user-images.githubusercontent.com/5937551/106731320-a42eb880-660f-11eb-8acc-f0d209240f78.png)

.NET Core:
![image](https://user-images.githubusercontent.com/5937551/106731344-a85ad600-660f-11eb-9cd0-3e7194ef2641.png)

**Comment by lkosson** [comment]
If you pass those values to DataSet as strings, check how you format them in your code; if you just `ToString()` them, it'll use current culture settings for formatting. If you pass them as a proper DateTime/Decimal, then check your report and field Language property and see if manually adding formatting to those TextBoxes changes anything.

**Comment by hovek** [comment]
They are passed by DataTable from the database directly in a correct data format e.g. DateTime or decimal. The report language is hr-HR (correct). The problems occur when the report uses default formatting for dateTime or currency:
![image](https://user-images.githubusercontent.com/5937551/107254271-709cc580-6a37-11eb-9b0b-cdd8c8e344e8.png)
![image](https://user-images.githubusercontent.com/5937551/107254344-7f837800-6a37-11eb-88e0-4f11822a7c2a.png)

**Comment by lkosson** [comment]
I'm not quite sure how to reproduce this behaviour locally. I have set report language to hr-HR without specifying format and get similar results as in your first screenshot. Please check in your regional Windows settings if you perhaps have custom date format string, try manipulating CultureInfo.CurrentCulture in your application or explicitly set CultureInfo.DateTimeFormat.LongDatePattern.
