### ISSUE TITLE
MVC Web 

### ISSUE THREAD

**Issue by DevLob-zz** [lkosson/reportviewercore#173]
is this working with MVC .net core also as i see you mention WinForm only also how to initialize
Stream reportDefinition; // your RDLC from file or resource
                                         // Assuming the namespace of your project is "YourNamespace"
               LocalReport1 report = new LocalReport1();
                report.LoadReportDefinition(reportDefinition);

**Comment by lkosson** [comment]
See project [ReportViewerCore.Sample.AspNetCore](https://github.com/lkosson/reportviewercore/tree/master/ReportViewerCore.Sample.AspNetCore) in this repo.

**Comment by DevLob-zz** [comment]
Many thanks great effort
