### ISSUE TITLE
CanGrow issue.

### ISSUE THREAD

**Issue by kc20230802** [lkosson/reportviewercore#174]
The CanGrow of field "Description" is set to true.

Issue 1: Occasionally some text may be overwritten by the following content due to its low height.
![image](https://github.com/lkosson/reportviewercore/assets/141216485/480a64ff-118a-407d-a2d4-9e1c09c25529)
![image](https://github.com/lkosson/reportviewercore/assets/141216485/86b25049-838a-4244-80fe-2eeaf12367ea)

Issue 2: Same content but sometimes show in two line, sometime show in three lines.
![image](https://github.com/lkosson/reportviewercore/assets/141216485/8a9a66e9-4347-4fc3-a5e9-04d267144a93)
![image](https://github.com/lkosson/reportviewercore/assets/141216485/b694cbb9-2fd7-4732-9c51-026bd9bd9d89)

**Comment by lkosson** [comment]
Can you reproduce the issue using one of sample projects in this repo (e.g. `ReportViewerCore.Sample.WinForms`)? Have you checked that in original ReportViewer the same report renders correctly?
