### ISSUE TITLE
RDLC with parameter throw exception when project be published with "PublishSingleFile

### ISSUE THREAD

**Issue by ericc8321** [lkosson/reportviewercore#175]
Attached a simplified project. It ran fine. However when I publish with:
```
<PublishSingleFile>true</PublishSingleFile>
<PublishReadyToRun>true</PublishReadyToRun>
```
It flow exception while rendering one RDLC with parameter. 
```
An error occurred during local report processing.
   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()
```

![image](https://github.com/lkosson/reportviewercore/assets/98855386/1f7f3cce-760b-46c4-9b84-2fa4f85f12bf)
![image](https://github.com/lkosson/reportviewercore/assets/98855386/7a84666b-f86b-42ba-babb-1231aaf546b8)
[ConsoleAppRDLC.zip](https://github.com/lkosson/reportviewercore/files/14255447/ConsoleAppRDLC.zip)

**Comment by lkosson** [comment]
Publishing to single file and/or AoT compilation won't work. See #49 for details.
