### ISSUE TITLE
File not found when connecting to SSRS

### ISSUE THREAD

**Issue by felixavendano** [lkosson/reportviewercore#176]
Hi,

I have this simple code and a report without parameters

The report name is hola.rdl and is in a Report server https://xxx.org/ReportServer/

Like this

![Imagen1](https://github.com/lkosson/reportviewercore/assets/86467016/a3da23b5-f336-4a81-aef0-b183589109ed)

This is the code I have

ServerReport report = new ServerReport(); 
report.ReportServerCredentials.NetworkCredentials = new NetworkCredential("xxx", "xxx", "xxx");
report.ReportServerUrl = new Uri("https://xxxxxxxx.org/ReportServer/");
report.ReportPath = "/Hola";
byte[] pdf = report.Render("PDF");

And when it comes to the last line I get an error  The system coudn´t find the specified file, I know what this means, but it seems to be everything correct.

I´m using .net core 6.0

Is there something I´m missing.

Thanks for any support on this

**Comment by lkosson** [comment]
Your code looks fine. Have you tried running it using original ReportViewer and get same error?

**Comment by felixavendano** [comment]
Thanks for your answer. What do you mean with original ReportViewer?

**Comment by lkosson** [comment]
I mean original package from Microsoft, targeting .NET Framework.

**Comment by felixavendano** [comment]
Ah, ok. No, what I did is to access through an iframe and it works fine except that is asking for credentials.
I will try what you suggest.
Thanks a lot.

**Comment by felixavendano** [comment]
Hi, the problem was thet two nugget packages where missing System.ServiceModel.Http and System.ServiceModel.Primitives
