### ISSUE TITLE
 Server report

### ISSUE THREAD

**Issue by josecalcano** [lkosson/reportviewercore#177]
Hello, good afternoon. I'm trying to make a call to a server report, and I want to add a header that specifies .Headers.Add("Accept", "text/html"), but it doesn't let me.

**Comment by lkosson** [comment]
Hi, this doesn't seem directly related to this project.

**Comment by josecalcano** [comment]
In your project to have 
ServerReport report = new ServerReport();
report.ReportServerCredentials.NetworkCredentials = new NetworkCredential("login", "password", "DOMAIN");
report.ReportServerUrl = new Uri("http://localhost/ReportServer");
report.ReportPath = "/Invoice";
report.SetParameters(new[] { new ReportParameter("Date", DateTime.Now.Date.ToString()) });
byte[] pdf = report.Render("PDF");

I need add a header to a report to accept html format

**Comment by lkosson** [comment]
I don't really understand what are you trying to do.

**Comment by lkosson** [comment]
I see. That most likely means either your Reporting Services URL is invalid, it doesn't work properly, or there are some problems with authentication. Reporting Services shouldn't respond with `text/html` under any normal circumstances.
