### ISSUE TITLE
Exception when using report viewer when publishing application into a single file.

### ISSUE THREAD

**Issue by akertesz-permaquim** [lkosson/reportviewercore#179]
It has been more than a year ago when we implemented this solution in order to show Reports in a Net 6 Winforms application, however, we've been having some issues once we want to publish the actual application to a single .exe. Whenever I try to generate a report, the following exception shows:

> An error occurred during local report processing.
>    at Microsoft.Reporting.WinForms.LocalReport.EnsureExecutionSession()
>    at Microsoft.Reporting.WinForms.LocalReport.SetParameters(IEnumerable`1 parameters)
>    at Permaquim.Counter.UI.Desktop.Forms.FormReport.GetUpdate()

The code that is throwing the exception:
```
    ReportParameter[] parameters = { new("emisionUser", DatabaseController.CurrentUser.NombreApellido),
                                new("image", "file:\\" + AppDomain.CurrentDomain.BaseDirectory + @"\Reports\ReportLogo.png"),
                                new("filtrosAplicados",GetFilterString())};

    this.reportViewer.LocalReport.SetParameters(parameters);
    SelectedShifts = shiftList.CheckedItems.OfType<CComboBoxItem<Entities.Relations.Operacion.Turno>>().ToList();
    this.reportViewer.LocalReport.DataSources.Add(new("ShiftDS", reportShifts));
    reportViewer.RefreshReport();

```

You can view the report viewer itself, however it does fail once I try to use it in any way shape or form.
This doesn't happen when I publish the project with all of its Dll files loose. Is there anything that can be done to solve this? 
Thanks a ton.

**Comment by lkosson** [comment]
Publishing to single file and/or AoT compilation won't work. #49 for details.

As a workaround, you can copy `Microsoft.CodeAnalysis.VisualBasic.dll` and all other missing DLLs mentioned in exception to your output directory, but then it won't really be a single file deployment.

**Comment by frankashley** [comment]
It has been a while since I figured out, a similar issue but I think it has something to do with this dance:
            var oBuilder = Host.CreateApplicationBuilder(args);
            string sPath = System.Reflection.Assembly.GetExecutingAssembly().Location;
            if (String.IsNullOrEmpty(sPath)){
                sPath = Environment.ProcessPath!; }

            string realPath = System.IO.Directory.GetParent(sPath)!.FullName;
            oBuilder.Configuration.SetBasePath(realPath);
            oBuilder.Configuration.AddJsonFile("appsettings.json");
            oBuilder.Environment.ContentRootPath = realPath;
            using IHost host = oBuilder.Build();
My particular case is .net 9 click once publishsinglefile, selfcontained , enablecompressioninsiunglefile. Also note I have to edit the publish settings by hand because the wizard messes it all up.
