### ISSUE TITLE
WinForms control designer,How to ues it normally with not programmatically？

### ISSUE THREAD

**Issue by dashengun** [lkosson/reportviewercore#187]
"WinForms control designer. To use ReportViewer in your WinForms project, add the control programmatically, as in ReportViewerCore.Sample.WinForms\ReportViewerForm.cs."

WinForms control designer,How to ues it normally with not programmatically？

Is there a plan to repair it in the foreseeable future?

Tks.

**Comment by lkosson** [comment]
No such plans right now. In principle it might be possible. If you feel like giving it a try:
 * grab `Microsoft.ReportViewer.Design.dll` from original Report Viewer
 * decompile it using `ILSpy`
 * add a new `Microsoft.ReportViewer.Designer` project to this repo
 * update `[Designer]` attribute on `Microsoft.Reporting.WinForms.ReportViewer`
 * fixup `EnvDTE` and `Microsoft.VisualStudio.Shell.*` references (if those even work in .NET Core)
 * fix any residual compilation errors
 * update `.nuspec` to include new project
