### ISSUE TITLE
Date formatting problems

### ISSUE THREAD

**Issue by Mek7** [lkosson/reportviewercore#189]
Looks like this is a similar problem to #17 
I have an RDLC report that has a TextRun defined like this:
```                    <TextRun>
                      <Value>= iif (First(Fields!InvoicePaymentConditionType.Value, "Table") = 0, "Deze nota wordt automatisch geïncasseerd", ("Wij verzoeken u dit bedrag voor "

+ DateAdd("d",First(Fields!InvoicePaymentTerm.Value, "InvoiceHeader"), First(Fields!InvoiceDate.Value, "Table"))
+ ", aan ons over te maken onder vermelding van factuurnummer" 
+ First(Fields!InvoiceNumber.Value , "Table") 
+ ", op bankrekeningnummer " 
+ First(Fields!CompanyBankAccount.Value, "InvoiceHeader")
+ "."))</Value>
                      <Style>
                        <FontSize>7pt</FontSize>
                        <Format>d-M-yyyy</Format>
                        <Color>=IIF (Globals!PageNumber &lt;&gt; 1, "White", IIF (Sum(Fields!InvoiceLineTotalAmount.Value, "Table") &lt; 0, "White", "Black"))</Color>
                        <Language>nl-NL</Language>
                      </Style>
                    </TextRun>
```
Field `InvoicePaymentTerm` is of type int. Field `InvoiceDate` is of type DateTime.
The problem is in the date format. In MS ReportViewer, it renders the text: "Wij verzoeken u dit bedrag voor 2-7-2023 ...etc", but in ReportViewer Core it is "Wij verzoeken u dit bedrag voor 02-07-2023 ...etc".
Date formatting is correct - it uses hyphens instead of slashes, it's just that there are leading zeroes added.
The RDLC file has top-level Language tag set to nl-NL and all TextRuns that contain locale-specific text (like currencies, amounts) also have Language set to nl-NL, like in the example above.
I have verified that the `Thread.CurrentThread.CurrentCulture` and `Thread.CurrentThread.CurrentUICulture` properties are the same as when the MS ReportViewer was used.
I would like to preserve the old behavior without leading zeroes on dates, but without modification of the RDLC as there are many in my system. What can I do, or is this a bug?

**Comment by Mek7** [comment]
Now I verified that it's a behavioral difference in DateTime.ToString() implementation between .NET Framework 4.8 and .NET.
This program (console app):
```
Console.WriteLine(new DateTime(2013, 2, 7).ToString(CultureInfo.GetCultureInfo("nl-NL")));
```
Writes date without leading zeroes in .NET Framework 4.8 and with leading zeroes in .NET.
I don't think there is anything we could do here...?

**Comment by lkosson** [comment]
I can't recall exact details, but there were some issues about using `CurrentCulture` vs `InvariantCulture` vs report-provided culture, causing ReportViewerCore to behave slightly different than original package.

As for your problem, try setting `CurrentCulture` to custom `CultureInfo` with `LongDatePattern` set to include leading zeros for day and month. Setting custom culture should work since #75.

**Comment by Mek7** [comment]
Thanks, that seems like a good idea.
Currently I have confirmation that this change in formatting in generated PDF files is not a problem, so I'm not going to dig into it further. Hopefully it helps someone else in the future.
