### ISSUE TITLE
the Gauge display Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by abaazzi** [lkosson/reportviewercore#19]
The Gauge display error message : **Object reference not set to an instance of an object**
![image](https://user-images.githubusercontent.com/8314262/108516161-2d0f4a80-72c6-11eb-871a-3ca0ae03df85.png)

**Comment by lkosson** [comment]
See if you get the same error if your gauge is set to a fixed value instead of being bound to a datasource. Also please provide a stacktrace of a first-chance NullReferenceException thrown when running your application under a debugger.

**Comment by abaazzi** [comment]
Hi Ikosson, 
Thank for your feedback, Yes i have the similar error with a gauge set to fixes value, i don't have any stacktrace, This error shewed on generated report.

**Comment by lkosson** [comment]
I have checked the gauge on some of my reports and it seems to work fine. Try re-adding a new gauge (with fixed value and no changed properties) to your report and see if it still shows an error. If it does, then see if you can replicate this behavior in one of the sample project in this repo. If it doesn't, then perhaps there is a computed style on your existing gauge that fails to compute somehow - try re-applying properties to this new gauge and see when it starts to fail again.

As for a stack trace - if you run your application from Visual Studio or other debugger and set in Exceptions window to break on first-chance NullReferenceException, you should see a full call stack where it occured even if it gets caught and is only displayed on a report.

**Comment by abaazzi** [comment]
in your example i have sumilar error 
![image](https://user-images.githubusercontent.com/8314262/108544214-740d3800-72e6-11eb-97fd-44a70bc033f8.png)

**Comment by lkosson** [comment]
I see. Radial gauge indeed is broken; I have used only linear ones. Hang on - should be easy to fix it.

**Comment by lkosson** [comment]
Version 15.1.10 is now available on NuGet. Radial gauges should be working correctly now.

**Comment by abaazzi** [comment]
Thank you
