### ISSUE TITLE
Cannot Install on .NET 8

### ISSUE THREAD

**Issue by rollinelactaoen** [lkosson/reportviewercore#190]
Cannot Install on .NET 8 due to conflicting dependencies using pre-released version. Is there any update on this?

**Comment by lkosson** [comment]
Write step by step how to reproduce the problem using new .NET project or using one of sample projects in this repo.

**Comment by rollinelactaoen** [comment]
![image](https://github.com/user-attachments/assets/1cc12860-10dc-4b18-b937-055f73759fa2)
![image](https://github.com/user-attachments/assets/9d5bb448-55a1-4f5c-ae3f-7aeaafbc9d5a)

**Comment by lkosson** [comment]
Try either downgrading `CodeGeneration` package to version 8.0.0 or do what the error message said.

**Comment by rollinelactaoen** [comment]
This solved the issue on installation, but I am no longer able to add view from the code generator.
![image](https://github.com/user-attachments/assets/04d7ef4c-f457-42d8-8157-adca36f65aa8)

**Comment by rollinelactaoen** [comment]
Downgrade `CodeGeneration` package version to 8.0.0 to install `ReportViewerCore` then install `CodeAnalysis` package version 4.8.0 to be able to update back to `CodeGeneration` package 8.0.3 to solve this issue.
