### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by heppth** [lkosson/reportviewercore#191]
Hi,

is it possible to render the report as CSV. Microsoft Report Builder has this functionality.

Thanks

**Comment by lkosson** [comment]
Hello,

it is not possible at the moment, but in principle it should be doable. CSV export is handled by `Microsoft.ReportingServices.Rendering.DataRenderer.CsvReport` renderer from `Microsoft.ReportingServices.DataRendering` assembly.

**Comment by heppth** [comment]
Thank you very much for your quick reply. Is there a change that `Microsoft.ReportingServices.DataRendering` will be part of this project?

**Comment by lkosson** [comment]
I'll look into it.

**Comment by lkosson** [comment]
With latest commit, CSV and XML renderers are now available. Compile the package from sources and see if it works with your reports. If it does, I'll upload _official_ package to NuGet.

**Comment by heppth** [comment]
Awesome. I tested it and it is working as expected. Thank you!

**Comment by lkosson** [comment]
Version 15.1.22 is now available on NuGet.
