### ISSUE TITLE
Problems .Net8 Microsoft.EntityframeworkCore.Design 8.0.8 with ReportViewerCore.NETCore 15.1.19 or upper

### ISSUE THREAD

**Issue by jvsancho80** [lkosson/reportviewercore#192]
Exist a conflict with 2 nuget package

![image](https://github.com/user-attachments/assets/2737f5ec-bf9a-403f-8a9d-f655f7420dad)

**Comment by lkosson** [comment]
Try manually resolving this conflict by explicitly referencing `Microsoft.CodeAnalysis.Common` in your project.

**Comment by jvsancho80** [comment]
I try to resolve the problem but is impossible. When I have added to resolve the conflict libraries and throw new migration return error . Aren't compatible the both libraries. Microsoft.CodeAnalysisCommon 4.8.0.3.final and Microsoft.CodeAnalisys.Common 4.5.0

**Comment by lkosson** [comment]
Seems to work fine out-of-the-box on VS 17.11.4, .NET 8 and a fresh project:

![image](https://github.com/user-attachments/assets/05db306c-7949-46ad-861d-588bb9061311)

`Microsoft.CodeAnalysis.CSharp.Workspaces` resolve to using `4.8.0-3.final` version of `Microsoft.CodeAnalysis.Common`.

**Comment by jvsancho80** [comment]
How to change Microsoft.CodeAnalysis.Common in Microsoft.EntityFrameworkCore.Design 8.0.8 at version 4.8.0-3.final?
If you throw a migration in this project works?

**Comment by jvsancho80** [comment]
It works ok. Thank you so much. But... Why use a preliminary version? Is not possible use the same version of Microsoft.EntityFreameworkCore.Design 8.0.8? I'm concerned that I will have problems with migration in the future.

**Comment by lkosson** [comment]
When .NET 8 was published, it referenced `4.8.0-3.final` version in some of the most popular assemblies, most notably in `Microsoft.VisualStudio.Web.CodeGeneration.Design` which is added by default in ASP.NET Core project template. If `ReportViewerCore` didn't use exact same version, everyone using this template would have to resolve conflict manually. To mitigate this, `ReportViewerCore` has been referencing same version of `Microsoft.CodeAnalysis.Common` as original release of each subsequent .NET version.

**Comment by jvsancho80** [comment]
Ok. But I don't understand why Microsoft.EntityFreameworkCore.Design 8.0.8 not use this version and use Microsoft.CodeAnalisys.Common 4.5.0

**Comment by lkosson** [comment]
`Microsoft.VisualStudio.Web.CodeGeneration.Design` now references proper release of `Microsoft.CodeAnalysis.Common` for more than 6 months. I guess it's good time to upgrade `ReportViewerCore` as well.

**Comment by lkosson** [comment]
Version 15.1.23 with updated references is now available on NuGet.

**Comment by jvsancho80** [comment]
Ok. Thank you so much.
