### ISSUE TITLE
Columns in report body

### ISSUE THREAD

**Issue by ashinek** [lkosson/reportviewercore#193]
Did anyone got problem with columns in report? He should treat columns as another page, and after fill it he should generete another page. In result he leaves column 2 blank, and start fill another page column 1.
![image](https://github.com/user-attachments/assets/3f26e9a3-0534-438b-80f8-d3ab5e8fcbba)
 I tried change width of column, but it nothing changing, also even try to use 3 columns, and scheme was the same. 1 collumn was filled with data from tabix, second column was blank, third also, and program continue generation from another page column 1

**Comment by lkosson** [comment]
Does this problem occur only in `ReportViewerCore`, while working fine in original Reporting Services / ReportViewer?

**Comment by ashinek** [comment]
Yes only on ViewerCore. In this particular case whe move to linux server from windows server, and started using your solution.

We use version 15.1.18

**Comment by lkosson** [comment]
Please provide exact steps to reproduce the problem, if possible using one of `ReportViewerCore.Sample.*` projects from this repo - either by modifying existing RDLC file or plugging in your own.

**Comment by ashinek** [comment]
Here is the file:

<?xml version="1.0" encoding="utf-8"?>
<Report xmlns="http://schemas.microsoft.com/sqlserver/reporting/2016/01/reportdefinition" xmlns:rd="http://schemas.microsoft.com/SQLServer/reporting/reportdesigner">
  <AutoRefresh>0</AutoRefresh>
  <DataSources>
    <DataSource Name="WWSSEModels">
      <ConnectionProperties>
        <DataProvider>System.Data.DataSet</DataProvider>
        <ConnectString>/* Local Connection */</ConnectString>
      </ConnectionProperties>
      <rd:DataSourceID>6331ee5a-50f9-480f-ac63-b236a96c7182</rd:DataSourceID>
    </DataSource>
  </DataSources>
  <DataSets>
    <DataSet Name="DataSet">
      <Query>
        <DataSourceName>WWSSEModels</DataSourceName>
        <CommandText>/* Local Query */</CommandText>
      </Query>
      <Fields>
        <Field Name="Classroom">
          <DataField>Classroom</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="Course">
          <DataField>Course</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="Date">
          <DataField>Date</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="End">
          <DataField>End</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="Info">
          <DataField>Info</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="Lecturer">
          <DataField>Lecturer</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
        <Field Name="Start">
          <DataField>Start</DataField>
          <rd:TypeName>System.String</rd:TypeName>
        </Field>
      </Fields>
      <rd:DataSetInfo>
        <rd:DataSetName>WWSSE.Models</rd:DataSetName>
        <rd:TableName>ScheduleDocModel</rd:TableName>
        <rd:ObjectDataSourceType>WWSSE.Models.ScheduleDocModel, WWSSE, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</rd:ObjectDataSourceType>
      </rd:DataSetInfo>
    </DataSet>
  </DataSets>
  <ReportSections>
    <ReportSection>
      <Body>
        <ReportItems>
          <Tablix Name="Tablix3">
            <TablixBody>
              <TablixColumns>
                <TablixColumn>
                  <Width>1.59606cm</Width>
                </TablixColumn>
                <TablixColumn>
                  <Width>7.09939cm</Width>
                </TablixColumn>
                <TablixColumn>
                  <Width>0.69648cm</Width>
                </TablixColumn>
              </TablixColumns>
              <TablixRows>
                <TablixRow>
                  <Height>0.52062cm</Height>
                  <TablixCells>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Textbox62">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value />
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                    <Color>Red</Color>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style>
                                <TextAlign>Center</TextAlign>
                              </Style>
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Textbox62</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Textbox63">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value>Rok akademicki </Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value>=Parameters!AcademicYear.Value</Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style>
                                <TextAlign>Center</TextAlign>
                              </Style>
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Textbox63</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                        <ColSpan>2</ColSpan>
                      </CellContents>
                    </TablixCell>
                    <TablixCell />
                  </TablixCells>
                </TablixRow>
                <TablixRow>
                  <Height>0.49417cm</Height>
                  <TablixCells>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Textbox53">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value>=Fields!Date.Value</Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                    <Color>Red</Color>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style>
                                <TextAlign>Center</TextAlign>
                              </Style>
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Textbox53</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Textbox54">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value />
                                  <Style />
                                </TextRun>
                              </TextRuns>
                              <Style />
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Textbox54</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Textbox55">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value />
                                  <Style />
                                </TextRun>
                              </TextRuns>
                              <Style />
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Textbox55</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                  </TablixCells>
                </TablixRow>
                <TablixRow>
                  <Height>0.6cm</Height>
                  <TablixCells>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Classroom">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value>=Fields!Start.Value</Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value> - </Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value>=Fields!End.Value</Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style>
                                <TextAlign>Center</TextAlign>
                              </Style>
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Classroom</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Course">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value>=Fields!Course.Value</Value>
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value> - </Value>
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value>=Fields!Lecturer.Value</Value>
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value xml:space="preserve"> </Value>
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                  </Style>
                                </TextRun>
                                <TextRun>
                                  <Value>=Fields!Info.Value</Value>
                                  <Style>
                                    <FontSize>8pt</FontSize>
                                    <Color>Red</Color>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style />
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Course</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                    <TablixCell>
                      <CellContents>
                        <Textbox Name="Classroom1">
                          <CanGrow>true</CanGrow>
                          <KeepTogether>true</KeepTogether>
                          <Paragraphs>
                            <Paragraph>
                              <TextRuns>
                                <TextRun>
                                  <Value>=Fields!Classroom.Value</Value>
                                  <Style>
                                    <FontSize>7pt</FontSize>
                                    <FontWeight>Heavy</FontWeight>
                                    <Color>Red</Color>
                                  </Style>
                                </TextRun>
                              </TextRuns>
                              <Style>
                                <TextAlign>Center</TextAlign>
                              </Style>
                            </Paragraph>
                          </Paragraphs>
                          <rd:DefaultName>Classroom1</rd:DefaultName>
                          <Style>
                            <Border>
                              <Color>LightGrey</Color>
                              <Style>Solid</Style>
                            </Border>
                            <PaddingLeft>2pt</PaddingLeft>
                            <PaddingRight>2pt</PaddingRight>
                            <PaddingTop>2pt</PaddingTop>
                            <PaddingBottom>2pt</PaddingBottom>
                          </Style>
                        </Textbox>
                      </CellContents>
                    </TablixCell>
                  </TablixCells>
                </TablixRow>
              </TablixRows>
            </TablixBody>
            <TablixColumnHierarchy>
              <TablixMembers>
                <TablixMember />
                <TablixMember />
                <TablixMember />
              </TablixMembers>
            </TablixColumnHierarchy>
            <TablixRowHierarchy>
              <TablixMembers>
                <TablixMember>
                  <KeepWithGroup>After</KeepWithGroup>
                </TablixMember>
                <TablixMember>
                  <Group Name="Date">
                    <GroupExpressions>
                      <GroupExpression>=Fields!Date.Value</GroupExpression>
                    </GroupExpressions>
                  </Group>
                  <TablixMembers>
                    <TablixMember>
                      <KeepWithGroup>After</KeepWithGroup>
                    </TablixMember>
                    <TablixMember>
                      <Group Name="Details" />
                    </TablixMember>
                  </TablixMembers>
                  <KeepTogether>true</KeepTogether>
                </TablixMember>
              </TablixMembers>
            </TablixRowHierarchy>
            <DataSetName>DataSet</DataSetName>
            <Top>1.2791cm</Top>
            <Left>0.28787cm</Left>
            <Height>1.61479cm</Height>
            <Width>9.39193cm</Width>
            <Style>
              <Border>
                <Style>None</Style>
              </Border>
            </Style>
          </Tablix>
          <Textbox Name="Textbox58">
            <CanGrow>true</CanGrow>
            <KeepTogether>true</KeepTogether>
            <Paragraphs>
              <Paragraph>
                <TextRuns>
                  <TextRun>
                    <Value>Plan zajęć </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!Year.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value> rok </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!Semester.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value> semestr</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                </TextRuns>
                <Style>
                  <TextAlign>Center</TextAlign>
                </Style>
              </Paragraph>
              <Paragraph>
                <TextRuns>
                  <TextRun>
                    <Value>=Parameters!AlbumType.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value> - </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!StudyType.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value xml:space="preserve"> </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!Faculty.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value xml:space="preserve"> </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!Specialization.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value xml:space="preserve"> </Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                  <TextRun>
                    <Value>=Parameters!AlbumType.Value</Value>
                    <Style>
                      <FontWeight>Heavy</FontWeight>
                    </Style>
                  </TextRun>
                </TextRuns>
                <Style>
                  <TextAlign>Center</TextAlign>
                </Style>
              </Paragraph>
            </Paragraphs>
            <rd:DefaultName>Textbox58</rd:DefaultName>
            <Left>0.28787cm</Left>
            <Height>1.10271cm</Height>
            <Width>9.39193cm</Width>
            <ZIndex>1</ZIndex>
            <Style>
              <Border>
                <Style>None</Style>
              </Border>
              <PaddingLeft>2pt</PaddingLeft>
              <PaddingRight>2pt</PaddingRight>
              <PaddingTop>2pt</PaddingTop>
              <PaddingBottom>2pt</PaddingBottom>
            </Style>
          </Textbox>
        </ReportItems>
        <Height>29.7cm</Height>
        <Style />
      </Body>
      <Width>9.84438cm</Width>
      <Page>
        <PageHeight>29.7cm</PageHeight>
        <PageWidth>21cm</PageWidth>
        <LeftMargin>0cm</LeftMargin>
        <RightMargin>0cm</RightMargin>
        <TopMargin>1cm</TopMargin>
        <BottomMargin>1cm</BottomMargin>
        <Columns>2</Columns>
        <ColumnSpacing>0.13cm</ColumnSpacing>
        <Style />
      </Page>
    </ReportSection>
  </ReportSections>
  <ReportParameters>
    <ReportParameter Name="AlbumType">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="Specialization">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="Faculty">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="Year">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="Semester">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="StudyType">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="StudyField">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
    <ReportParameter Name="AcademicYear">
      <DataType>String</DataType>
      <Nullable>true</Nullable>
      <AllowBlank>true</AllowBlank>
      <Prompt>ReportParameter1</Prompt>
    </ReportParameter>
  </ReportParameters>
  <ReportParametersLayout>
    <GridLayoutDefinition>
      <NumberOfColumns>4</NumberOfColumns>
      <NumberOfRows>2</NumberOfRows>
      <CellDefinitions>
        <CellDefinition>
          <ColumnIndex>0</ColumnIndex>
          <RowIndex>0</RowIndex>
          <ParameterName>AlbumType</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>1</ColumnIndex>
          <RowIndex>0</RowIndex>
          <ParameterName>Specialization</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>2</ColumnIndex>
          <RowIndex>0</RowIndex>
          <ParameterName>Faculty</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>3</ColumnIndex>
          <RowIndex>0</RowIndex>
          <ParameterName>Year</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>0</ColumnIndex>
          <RowIndex>1</RowIndex>
          <ParameterName>Semester</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>1</ColumnIndex>
          <RowIndex>1</RowIndex>
          <ParameterName>StudyType</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>2</ColumnIndex>
          <RowIndex>1</RowIndex>
          <ParameterName>StudyField</ParameterName>
        </CellDefinition>
        <CellDefinition>
          <ColumnIndex>3</ColumnIndex>
          <RowIndex>1</RowIndex>
          <ParameterName>AcademicYear</ParameterName>
        </CellDefinition>
      </CellDefinitions>
    </GridLayoutDefinition>
  </ReportParametersLayout>
  <ConsumeContainerWhitespace>true</ConsumeContainerWhitespace>
  <rd:ReportUnitType>Cm</rd:ReportUnitType>
  <rd:ReportID>4443952b-9a70-42f5-a4d2-e276e59f4e04</rd:ReportID>
</Report>

If you put data to tablix you will see how it filling columns

**Comment by ashinek** [comment]
[test.docx](https://github.com/user-attachments/files/17161549/test.docx)

Sorry for format of file inside is copy from RDLC file we using.

If you send data you will se how tabix is filling collumns

**Comment by lkosson** [comment]
As far as I can tell, your report works exactly the same both in original Report Viewer (left) and in ReportViewerCore (right):

![Comparison](https://github.com/user-attachments/assets/39a033c5-ab54-4f53-b6ba-09dd821a7fff)

Add a screenshot of the same report using your data showing both how it used to render and how it renders now.

**Comment by ashinek** [comment]
Look this is how looks now:
![image](https://github.com/user-attachments/assets/7cb7172c-af0b-4bb4-b65d-de7a22fb3a71)
and how it looks on older version
![image](https://github.com/user-attachments/assets/d6badd95-8ed2-4ce5-86c3-8d8526a25378)
the same RDLC file

**Comment by lkosson** [comment]
Oh, now I see what you mean.

**Comment by lkosson** [comment]
Using provided RDLC and large enough dataset, I get two column layout on both original and RVC package:
![img](https://github.com/user-attachments/assets/fb0d233e-9583-4a6c-b92a-e837cbacedf2)

So the feature seems to work fine. I'd suggest checking if both of your applications use same exact printer settings (paper size, margins etc) and use same data source (your screenshot shows clearly different date ranges).

If all fails, provide a way to reproduce the problem using self-contained application based on `ReportViewerCore.Sample.*` from this repo. Without it, I won't be able to help you any further.
