### ISSUE TITLE
Error rendering images with new NuGet version 15.1.22

### ISSUE THREAD

**Issue by dsantos1998** [lkosson/reportviewercore#194]
Hi all,

I have a .NET 8 web project using version 15.1.21 and the generation of .doc/.docx reports works correctly. The problem came when I wanted to build the new image with version 15.1.22 (the most recent one). Before you send me to the "Linux rendering solution" section, let me tell you that it loads the libraries related to the GDI+ plugin from my Dockerfile in the container and with the previous version, everything works correctly. For your interest, I load it like this:

<code>apt-get update && apt-get install -y --no-install-recommends libc6-dev libgdiplus libx11-dev libxtst6 libxrender1 libxcb1 libx11-6 libsm6 libice6 libglib2.0-0 libfontconfig1 libfreetype6 libxft2 libxi6 libxrandr2 libxcursor1 libxinerama1 libpango1.0-0 libpangocairo-1.0-0 libatk1.0-0 libcairo2 libgdk-pixbuf2.0-0 libjpeg-dev libtiff-dev libgif-dev libharfbuzz-dev libwebp-dev</code>

I have seen that the libraries for .NET 8 are updated from the following way:
__System.Drawing.Common 4.7.2 -> System.Drawing.Common 8.0.0__
__System.ServiceModel.Http 4.8.1 -> System.ServiceModel.Http 6.0.0__

I have tried to look for any compatibility issues with the __System.Drawing.Common 8.0.0__ library and GDI+ but found nothing..

The error that Visual Studio 2022 returns is: __<mark>System.drawing.common the type initializer for 'gdip' threw an exception</mark>__

**Comment by lkosson** [comment]
Non-windows support for `System.Drawing.Common` has been [deprecated in .NET 6](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) and [removed completely in .NET 7](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/system-drawing).

**Comment by dsantos1998** [comment]
Thank you!

I will still using the previous version.

**Comment by dsantos1998** [comment]
Thank you!

I will still using the previous version.
