### ISSUE TITLE
Is there any Asynchronous Streaming option?

### ISSUE THREAD

**Issue by sraban75** [lkosson/reportviewercore#195]
I have a .net core ERP solution, there are almost 500+ reports we made using RDLC,
and everything is fine, there is no issue in RDLC, but it's prolonged compared to other reporting like FastReport.Net.
like for a single invoice page, it takes 3 to 4 seconds to convert XML to PDF and send it to the client (angular) as a blob file, and angular again converts that file to PDF from the blob and then renders the pdf viewer.
so if my report contains more than 100+ pages, it takes more time to convert again from XML to PDF create a blob file, and send it to the client.

how can we make this faster? suppose, in old MVC, the report viewer handles this, the report viewer loads data in lazy mode using pagination and renders faster, but here, we need to generate the full report first, and then send it to the client, this is the problem.

**Comment by lkosson** [comment]
You can render specific pages of your report as HTML or PDF, as in original Report Viewer - see #35.
