### ISSUE TITLE
External images are not rendered for the URL's versioned using OpenAPI specification/Swagger

### ISSUE THREAD

**Issue by bibing1988** [lkosson/reportviewercore#197]
The SSRS reports are not rendering the external images when the URL (an .net core API project) is OpenAPI specification versioned.

Request Reponse header.
![image](https://github.com/user-attachments/assets/6bd1d51f-bdf8-4f52-8cf2-81517cd209d9)

Image not rendered in report
![image](https://github.com/user-attachments/assets/132ebbd0-e6d2-41f7-ad24-d7b7e75b1118)

When I remove the versioning for the same endpoint, the images are rendered correctly.

![image](https://github.com/user-attachments/assets/6bd1d51f-bdf8-4f52-8cf2-81517cd209d9)

![image](https://github.com/user-attachments/assets/dc51eee9-fa81-4181-8796-89f0b7b9debc)

**Comment by bibing1988** [comment]
Uploaded wrong image. (First image, the response header when the api versioning is done)
![image](https://github.com/user-attachments/assets/9f9475ef-3276-4086-8722-d6d3ace49ec1)

**Comment by lkosson** [comment]
Provide a minimal project based on `ReportViewerCore.Sample` in this repo which reproduces the behavior.

**Comment by bibing1988** [comment]
[Projects.zip](https://github.com/user-attachments/files/17495727/Projects.zip)

Sample project with the error is attached.

Sample output from the example.
![image](https://github.com/user-attachments/assets/2cb5fe43-9923-4d51-a75a-f3c4400948f4)

**Comment by lkosson** [comment]
I see. ReportViewer indeed validates received `Content-Type` of images and reject anything other than `image/bmp`, `image/jpeg`, `image/gif`, `image/png`, `image/x-png`. This behavior is the same as in original ReportViewer/SSRS.
