### ISSUE TITLE
Microsoft.CodeAnalysis.Common reference pre-release version conflict

### ISSUE THREAD

**Issue by waxwing** [lkosson/reportviewercore#198]
The reference for Microsoft.CodeAnalysis.Common is using a pre-release version (4.8.0-3.final) which is giving me package conflicts with webcodgeneration. Please could the reference be changed to be the standard package to remove this issue? Thanks!

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.8.0 directly to project Inline Core to resolve this issue. 
[My project] -> Microsoft.VisualStudio.Web.CodeGeneration.Design 8.0.6 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 8.0.6 -> Microsoft.VisualStudio.Web.CodeGeneration 8.0.6 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 8.0.6 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 8.0.6 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 8.0.6 -> Microsoft.VisualStudio.Web.CodeGeneration.Utils 8.0.6 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0) 
[My project] -> ReportViewerCore.NETCore 15.1.22 -> Microsoft.CodeAnalysis.VisualBasic 4.8.0-3.final -> Microsoft.CodeAnalysis.Common (= 4.8.0-3.final).	Inline Core	D:\paperline.co.uk\Solution\InLine Core\Inline Core.csproj	1

**Comment by lkosson** [comment]
Version 15.1.23 with updated references is now available on NuGet.
