### ISSUE TITLE
UITypeEditor exists in both Microsoft.ReportViewer.DataVisualization and System.Windows.Forms

### ISSUE THREAD

**Issue by StefanMyczko** [lkosson/reportviewercore#20]
Create a Net5 windows forms application, and add the reportviercore.winforms nuget library, then enter the following

System.Drawing.Design.UITypeEditor oTest = new System.Drawing.Design.UITypeEditor();

It will fail to compile as this class is duplicated in System.Windows.Forms (net5-windows) and Microsoft.ReportViewer.DataVisualization (reportviercore.winforms nuget)

All the other classes in the System.Drawing.Design namespace exists only in:-

Assembly System.Windows.Forms.Design.Editors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

But UITypeEditor exists in:-

Assembly System.Windows.Forms.Design.Editors, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
and
Assembly Microsoft.ReportViewer.DataVisualization, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by lkosson** [comment]
Confirmed. System.Drawing.Design.UITypeEditor in Microsoft.ReportViewer.DataVisualization is no longer used. I'll remove it.

As a workaround until new nuget package is available set alias on ReportViewerCore.WinForms package reference in your project to `rv`, add `extern alias rv` and reference ReportViewer types using `rv::` specifier.
