### ISSUE TITLE
Couldn't add it to .net 8 wpf app

### ISSUE THREAD

**Issue by romandrovich** [lkosson/reportviewercore#201]
I created a new .net 8 WPF app. Added Microsoft.Core.Analysis 4.8.0 but on attempt to add ReportViewerCore.WinForms I get an error.
![{143CCBB0-232A-4A78-B60C-E7DE4BCEE0E4}](https://github.com/user-attachments/assets/7d1d8de1-6d27-4b5a-8a78-fabd49ded5c3)

**Comment by lkosson** [comment]
Seems to work fine on VS2022 17.12 and new WPF app template. Provide step by step description how to reproduce the behavior.
