### ISSUE TITLE
Need help with datasets

### ISSUE THREAD

**Issue by verloka** [lkosson/reportviewercore#22]
Is there a way to get the dataset query in a local report?
As an example: 
### _select * from calls_

![image](https://user-images.githubusercontent.com/5623092/110097021-3e1c8900-7da7-11eb-90a9-ab2811520587.png)

**Comment by lkosson** [comment]
In RDLCs data source is provided by external code - either explicitly by you or as a `BindingSource` by WinForms designer and databinding mechanism. I don't think there is a way to embed a query inside RDLC like it's done in RDL.

If you have such report and it fails to load/render using this project, please provide the RDLC file.

**Comment by verloka** [comment]
> In RDLCs data source is provided by external code - either explicitly by you or as a `BindingSource` by WinForms designer and databinding mechanism. I don't think there is a way to embed a query inside RDLC like it's done in RDL.
> 
> If you have such report and it fails to load/render using this project, please provide the RDLC file.

No, I'm asking if I can programmatically get the datasource query from the rdlc file using this library?

**Comment by lkosson** [comment]
I don't think so.
