### ISSUE TITLE
Report with Date parameters crashes + Fix

### ISSUE THREAD

**Issue by CorsairRO** [lkosson/reportviewercore#23]
Hello, i've been testing my reports back and forth now. 

I think i will keep a copy local on my comp for the moment as i would like to do some customizations in reportviewer that i would have wanted to do for AGES now.
Like removing Export to all crap not ever used, like TIFF, Web Archive, xml and so on. Leave only PDF / Excel / Word there.
Also print button you CANNOT configure to print Directly to a specific printer and so on

I discovered a bug and i've applied a quick fix for it. If your report has a date parameter it wants to show a datepicker
This crashes now in : 
Namespace: Microsoft.Reporting.WinForms
File: TextBoxWithImage
Line: Image image = new Bitmap(Assembly.GetExecutingAssembly().GetManifestResourceStream(imageResource));

After a quick investigation over manifest resources from the assembly, i've applied the current fix before calling the method:
imageResource = imageResource.Replace( ".Resources" , ".Resources.Resources" );

For some reason the resources are embedded with double resources folder, and they are accessed with only one.
This applies to All resources from there i think. 
Mine particular was Resources.16cal.gif that tries to show a calendar icon.

Thank you again for your help regarding server side reports
Have a nice day

**Comment by lkosson** [comment]
Thanks - I've made a typo in csproj when re-adding resources after decompilation - that's why there is ".Resources.Resources" on this one file. Fixed now.
