### ISSUE TITLE
Added 2 customizations in ReportViewer (Direct Export to a PDF File + Direct Print to a specific printer ) - no Dialogs

### ISSUE THREAD

**Issue by CorsairRO** [lkosson/reportviewercore#24]
Hello.

As like i said i am going to use my local version for further customizations, i have just made 2 that are VERY important for our products.

I dont know how to create a thing that is NOT an issue in here.

I have a reference now to a dummy Winforms.ReportViewer that i am not showing anywhere.
Just set report + params and calls the 2 new direct features. Before i was calling from my code the asmx webservice with specific calculations for page margins and sizes ( Very Important for Label Printing )

- Direct Export to a PDF File passed from app.
public string ExportToPdfFile( string fileName ) {

			var ErrorMessage = "OK";

			try {

				string m_mainStreamMimeType;

				string m_mainStreamFileNameExt;

				using ( var stream = new MemoryStream( ) ) {

					this.ServerReport.InternalRender(
						isAbortable: true ,
						"PDF" ,
						null , // DeviceInfo
						new NameValueCollection {
							{
								"rs:PageCountMode",
								m_pageCountMode.ToString()
							}
						} ,
						stream ,
						out m_mainStreamMimeType ,
						out m_mainStreamFileNameExt );
					stream.Position = 0L;
					stream.Position = 0L;
					var m_mainStreamBytes = new byte[ stream.Length ];
					stream.Read( m_mainStreamBytes , 0 , (int)stream.Length );

					using ( var fs = new FileStream( fileName , FileMode.OpenOrCreate ) ) {
						fs.Write( m_mainStreamBytes , 0 , m_mainStreamBytes.Length );
					}

				}

			}
			catch ( Exception e2 ) {
				UpdateUIState( e2 );
				ErrorMessage = e2.Message + "\n\n" + e2.StackTrace;
			}

			return ErrorMessage;
		}

- Direct Print a report to a specific printer ( no popup for selecting anything )
public string ExportToPrinter( string printerName ) {

			var ErrorMessage = "OK";

			try {

				string deviceInfo = CreateEMFDeviceInfo( 0 , 0 );
				ProcessAsyncInvokes( );
				BeginAsyncRender(
					"IMAGE" ,
					allowInternalRenderers: true ,
					deviceInfo ,
					PageCountMode.Estimate ,
					CreateStreamEMFPrintOnly ,
					OnRenderingCompletePrintOnly ,
					new PostRenderArgs( isDifferentReport: false , isPartialRendering: false ) ,
					requireCompletionOnUIThread: false
				);

				ReportPrintDocument reportPrintDocument = new ReportPrintDocument(
					CurrentReport.FileManager , (PageSettings)PageSettings.Clone( )
				);
				reportPrintDocument.DocumentName = Report.DisplayNameForUse;
				var ps = CreateDefaultPrintSettings( );
				ps.PrinterName = printerName;
				reportPrintDocument.PrinterSettings = ps;
				reportPrintDocument.Print( );

			}
			catch ( Exception e2 ) {
				UpdateUIState( e2 );
				ErrorMessage = e2.Message + "\n\n" + e2.StackTrace;
			}

			return ErrorMessage;
		}

**Comment by lkosson** [comment]
Hi,
feel free to create a fork of this project with your changes. I'll keep my version as close to original Report Viewer as possible.
