### ISSUE TITLE
Do you have an example of how to access reports from a remote SSRS server?

### ISSUE THREAD

**Issue by sarchibald-mdsol** [lkosson/reportviewercore#26]
Your examples are all for local reports. Yet your .md file says remote services should work. Can you provide an example of how to load the remote report definitions?

**Comment by lkosson** [comment]
There is a project `ReportViewerCore.Sample.WinFormsServer` in this repo using Reporting Services to display a remote report. Key part is:

	reportViewer.ProcessingMode = ProcessingMode.Remote;
	reportViewer.ServerReport.ReportServerCredentials.NetworkCredentials = new NetworkCredential("login", "password", "DOMAIN");
	reportViewer.ServerReport.ReportServerUrl = new Uri("http://localhost/ReportServer");
	reportViewer.ServerReport.ReportPath = "/Invoice";
	reportViewer.ServerReport.SetParameters(new[] { new ReportParameter("Title", "Invoice 4/2020") });
	reportViewer.RefreshReport();
