### ISSUE TITLE
Unable to use Nuget package.

### ISSUE THREAD

**Issue by dargavin** [lkosson/reportviewercore#29]
Happens both in projects using either ,net core 3.1 or  .Net 5

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.6.0 directly to project OHADST.Compass.Management to resolve this issue. 
 OHADST.Compass.Management -> ReportViewerCore.NETCore 15.1.11 -> Microsoft.CodeAnalysis.VisualBasic 3.6.0 -> Microsoft.CodeAnalysis.Common (= 3.6.0) 
 OHADST.Compass.Management -> Microsoft.VisualStudio.Web.CodeGeneration.Design 3.1.3 -> Microsoft.VisualStudio.Web.CodeGenerators.Mvc 3.1.3 -> Microsoft.VisualStudio.Web.CodeGeneration 3.1.3 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 3.1.3 -> Microsoft.VisualStudio.Web.CodeGeneration.Core 3.1.3 -> Microsoft.VisualStudio.Web.CodeGeneration.Templating 3.1.3 -> Microsoft.CodeAnalysis.CSharp 3.3.1 -> Microsoft.CodeAnalysis.Common (= 3.3.1).	OHADST.Compass.Management	D:\Dev\Visual Studio 2019\CompassManagement\OHADST.Compass.Management\OHADST.Compass.Management.csproj	1

**Comment by lkosson** [comment]
Try explicily referencing Microsoft.CodeAnalysis.Common 3.6.0 nuget package in your project.
