### ISSUE TITLE
Error when calling report.GetParameters()

### ISSUE THREAD

**Issue by DadvDadv** [lkosson/reportviewercore#30]
Hi,
I was testing your code and for a wile all was ok, but when i add a parameter, everything stop working :
```
My code :

var report = new LocalReport();

            report.LoadReportDefinition(new MemoryStream(Resources.Report1));
            
            var parameters = report.GetParameters(); // ERROR !!

            var dataSources = report.GetDataSourceNames();

            Random random = new Random();
            int i = random.Next(100);

            ProjibatDataSource projibatDataSource = new ProjibatDataSource();

            for (int j = 0; j < i; j++)
            {
                var customer = (CustomersRow)projibatDataSource.Customers.NewRow();
                customer.CustomerId = j;

                projibatDataSource.Customers.Rows.Add(customer);
            }



            foreach (var dataSource in dataSources)
            {
                report.DataSources.Add(new ReportDataSource(dataSource, (DataTable)projibatDataSource.Customers));
            }



            foreach (var parameter in parameters)
            {
                report.SetParameters(new ReportParameter(parameter.Name, i.ToString()));
            }

            var word = report.Render("WORDOPENXML");
```
Error: 

 Microsoft.ReportViewer.NETCore: An error occurred during local report processing. Microsoft.ReportViewer.Common: The definition of the report '' is invalid. Microsoft.ReportViewer.Common: An unexpected error occurred in Report Processing. Microsoft.ReportViewer.Common: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. File not found

[Report1.zip](https://github.com/lkosson/reportviewercore/files/6280267/Report1.zip)
[ProjibatDataSource.Designer.zip](https://github.com/lkosson/reportviewercore/files/6280268/ProjibatDataSource.Designer.zip)

If i remove the parameter, all work fine

**Comment by lkosson** [comment]
Hello,

your code looks fine. Check if your project has explicit dependency on `Microsoft.CodeAnalysis` package and - if so - try upgrading it to version 3.6.

**Comment by DadvDadv** [comment]
I follow the error until this line : 

https://github.com/lkosson/reportviewercore/blob/0772e6cfa95620347708777b71dd55856edd24ac/Microsoft.ReportViewer.Common/Microsoft.ReportingServices.RdlExpressions/ExprHostCompiler.cs#L276

I think it is a parse error because if i try your console sample app all work fine.

Can you try it with my sample project please ? 
I'm trying to integrate your project in an Azure function.

Thx

[FunctionApp1.zip](https://github.com/lkosson/reportviewercore/files/6284444/FunctionApp1.zip)

**Comment by lkosson** [comment]
I don't have much experience working with Azure, so I can't properly test your sample project. When converted to console application it indeed works fine. From what I see, it's still missing `Microsoft.CodeAnalysis` nuget package reference. Try adding it to your project directly.

As for location of the error - this project uses Roslyn VB compiler, which uses `Microsoft.CodeAnalysis`. The line you've linked is the first (and only) reference to the compiler itself. This call triggers loading of VB compiler and its dependencies. Somehow file `Microsoft.CodeAnalysis.dll` is missing and hence error. When running your project as a console application, this file correctly gets copied to the output directory.

**Comment by DadvDadv** [comment]
I think i got it...

I try to add reference to the dll in the project but there is no change, but i see that the function create a shadow bin directory for compiling, and there is no Microsoft.CodeAnalysis.dll inside.

If i copy it manualy 'after' debuging start, everythink work fine.

Probabely a specific mecanism for Azure Function.. i'll try to look how to add this dll inside the shadow bin directory.

What it is strange is that it well copy Microsoft.CodeAnalysis.VisualBasic.dll but not  Microsoft.CodeAnalysis.dll  ...

Thx for the help

**Comment by DadvDadv** [comment]
For other people who have the same issue you need to add : 

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    **<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>**
  </PropertyGroup>

in the project file (csproj)
