### ISSUE TITLE
Trouble loading image from varbinary(max) to Report

### ISSUE THREAD

**Issue by cook0318** [lkosson/reportviewercore#32]
Hello,

I have an image stored in a database as type `varbinary(max)`. In my .RDLC file, I have an image, with the appropriate Value, Source, and MIMEType set. I'm using EF to fill a a dataset I use as the report datasource. The column in my dataset is of datatype "String".

This is how I'm filling my dataset:

`myDataSet.ImageColumn = myImageAsByteArray.ToString()` 

The .xsd Dataset gives me no option to set the datatype as byte[] or varbinary, that's why I'm using a string.

When I do this, I get the Exception: `KeyNotFoundException: The given key "InvalidImage" was not present in the dictionary.`

Any help is appreciated, thank you in advance!

**Comment by lkosson** [comment]
Hi,

there are two problems:

1. When trying to pass image blob as a string to a report, use base64 encoding: `myDataSet.ImageColumn = Convert.ToBase64String(myImageAsByteArray)`. Using `ToString` on `byte[]` produces "System.Byte[]" string, which isn't a proper image and renderer tries to use "InvalidImage" placeholder instead.
2. "InvalidImage" resource is indeed missing in this project. I'll re-add it in a moment, but passing correct image data should be enough to fix the issue.

**Comment by cook0318** [comment]
That worked, thank you so much and thank you for developing this repo. It's the best of it's kind without a doubt!
