### ISSUE TITLE
ReportViewerCore.NETCore Package Error

### ISSUE THREAD

**Issue by HirenVekaria** [lkosson/reportviewercore#33]
![image](https://user-images.githubusercontent.com/74296705/114306706-54caa400-9afa-11eb-84b3-35c3861e4045.png)

Hi I am installing ReportViewerCore.NETCore in my .NET Core application, above error occurred. My application target framework is .NET Core 3.1, Can you help me, please?

Also By this package Can we load SSRS report in report viewer?

**Comment by lkosson** [comment]
Hello. Either manually add package `Microsoft.CodeAnalysis.Common` 3.6.0 to your project or remove package `Microsoft.VisualStudio.Web.CodeGeneration`.

This package don't have `ServerReport` required to interact with SSRS. There is one in `ReportViewerCore.WinForms` package. I guess it could be ported back here.

**Comment by lkosson** [comment]
I have just added `ServerReport` to `ReportViewerCore.NETCore` project. By using version compiled from this repo, you should be able to load render SSRS.

**Comment by HirenVekaria** [comment]
Thanks,

Can you send example how we can load ssrs report directly to report viewer
in .Net Core 3.1

**Comment by lkosson** [comment]
See the `ReportViewerCore.Sample.WinFormsServer` project in this repo. For ASP.NET Core, use the 2nd snippet from a readme.

**Comment by HirenVekaria** [comment]
I have Asp.Net Core web application n this application can I use
ReportViewerCore.Sample.WinFormsServer package

**Comment by lkosson** [comment]
`ReportViewerCore.Sample.WinFormsServer` is not a package - it is a sample showing how to use Reporting Services in WinForms application.

For ASP.NET Core applications, either compile `ReportViewerCore.NETCore` project from this repo by yourself or wait a bit for a new nuget package which includes `ServerReport`.

**Comment by HirenVekaria** [comment]
Ok, thanks,

Can you tell me how long we have to wait for next git release for use of
server report?

**Comment by lkosson** [comment]
The package version 15.1.12 should be already available on nuget.

**Comment by HirenVekaria** [comment]
Ok, by using this package we can load ssrs report in report viewer in .Net
Core web application, right?

**Comment by lkosson** [comment]
"Report viewer", as in interactive web page allowing user to view, sort and export report from SSRS? No. If you have your reports on SSRS, this package allows you to run and render them to PDF/HTML/XLSX etc. Only way to get interactive, web-based report viewer is to point your users directly to Reporting Services URL.

**Comment by HirenVekaria** [comment]
OK, thanks for great support.

**Comment by rungsoso** [comment]
> HTML

How to web page (RazorPage) render HTML Please give me an example.
