### ISSUE TITLE
Can give an example how to use subreport with your packages

### ISSUE THREAD

**Issue by avikunnure** [lkosson/reportviewercore#34]
Please give me example how to create subreport

**Comment by lkosson** [comment]
Using subreports should be exactly the same as in original ReportViewer - create a separate RDLC, add it to your main RDLC, set up datasource and parameters binding and load definitions using `LocalReport.LoadSubreportDefinition(string, Stream)` with the same name as specified on Subreport item on your main RDLC.

**Comment by limanshun** [comment]
when i use subreport  show me miss parameters ,How to write paramerters to  subreport

**Comment by limanshun** [comment]
when i use subreport show me missing parameters ,How to write paramerters to the subreport

**Comment by lkosson** [comment]
Subreport processing works the same way as in official packages.
