### ISSUE TITLE
Pagination on UI

### ISSUE THREAD

**Issue by nshekhar1** [lkosson/reportviewercore#35]
I am using this project with .Net 5 and trying to show report on UI. I have used the html response to show the report. Is there a way to implement pagination or  I have to download the whole report?

**Comment by lkosson** [comment]
You can get a specific page by passing `Section` parameter in `deviceInfo` argument to `Render` method, e.g.: `report.Render("HTML5", "<DeviceInfo><Section>15</Section></DeviceInfo>")`.

**Comment by nshekhar1** [comment]
Works for me. Thanks for the response.
