### ISSUE TITLE
Page Numbering in DocX always 1 of 1

### ISSUE THREAD

**Issue by g136660** [lkosson/reportviewercore#37]
Page Numbering in DocX always 1 of 1
[TORG29_NAL_WITH_DIS_EX.zip](https://github.com/lkosson/reportviewercore/files/6345411/TORG29_NAL_WITH_DIS_EX.zip)

**Comment by lkosson** [comment]
To use Word's own page numbering, instead of manually building string in TextBox expression, construct it from textruns like this:
![obraz](https://user-images.githubusercontent.com/22995707/115501947-6b989580-a274-11eb-8137-079e5e2dd0ab.png)

**Comment by g136660** [comment]
I know size of a page.
Is it possible to split a docx pages in separate files in render process?
There is no way split docx by pages anywhere.

**Comment by g136660** [comment]
I'm looking for any way to get PDF from the available formats via convertion.

**Comment by lkosson** [comment]
I don't think there is a way to render a specific page to docx. There are, however, tools to manipulate docx documents - you might try to use them to extract a single page.
