### ISSUE TITLE
Getting a slue of File not found errors around WCF and .NET Core 5

### ISSUE THREAD

**Issue by nportelli** [lkosson/reportviewercore#39]
Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.8.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

I installed the nuget package for the assembly above, then get one for System.ServiceModel.Http, Version=4.8.1.0

Guessing because core did away with WCF?  I'll try and keep installing nuget packages and see what happens.

**Comment by lkosson** [comment]
Please provide full stack trace where the exception is thrown.
