### ISSUE TITLE
Report Data datasource error.

### ISSUE THREAD

**Issue by rodriguez90** [lkosson/reportviewercore#40]
Hello guys, I have this error when setting up a new data source.
Thanks.

![image](https://user-images.githubusercontent.com/15237850/116631277-bb392a00-a922-11eb-96d7-c56d8245e28f.png)

**Comment by lkosson** [comment]
Hi. This doesn't seem related to the project - report designer is a separate, unchanged component of VS.

**Comment by g136660** [comment]
This editor is buggy. You need create dataset outside rdlc editor and add already created dataset in rdlc editor.

**Comment by lkosson** [comment]
But still - you can use report designer without even referencing this package. While it indeed is kind of bugged when trying to add a datasource, fixing that is beyond the scope of this project.

**Comment by rodriguez90** [comment]
OK @lkosson , I got it, Thanks

**Comment by lkosson** [comment]
I have updated a readme file with a short guide how to create a new dataset for classes in your project without using external report editor or manually changing `.rdlc` file.
