### ISSUE TITLE
ServerReport Issue + Solution for having Server on HTTPS.

### ISSUE THREAD

**Issue by CorsairRO** [lkosson/reportviewercore#43]
Hello, 

i found an issue with the Server Reports. The render fails if the server is on HTTPS.

Solution:
Project: Microsoft.Reporting.WinForms
Folder: Microsoft.Reporting.WinForms.Internal.Soap.ReportingServices2005.Execution
Class: ReportExecutionServiceSoapClient
Method: public ICredentials Credentials - set

Replace: binding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
with:

if ( Url.StartsWith( "https" ) ) {
	binding.Security.Mode = BasicHttpSecurityMode.Transport;
}
else {
	binding.Security.Mode = BasicHttpSecurityMode.TransportCredentialOnly;
}

**Comment by lkosson** [comment]
Thanks. I have no way to verify this, but the change looks OK.

**Comment by CorsairRO** [comment]
Hello, yes, I know you have no scenario to check it.

I tried in my production apps now and it is working well for both HTTP and HTTPS servers

Just in case somebody else misses this functionality.

Have a nice day there,


Thank you / Tak / Multumesc

Cosmin Palade
Senior Developer
Phone: +40 744 535 995
Email: ***@***.******@***.***>
Skype: cosmin.palade
Teams: ***@***.******@***.***>
Web: http://www.lundin.ro<http://www.lundin.ro/>

**Comment by g136660** [comment]
Server reports working on Linux?

**Comment by CorsairRO** [comment]
hello,

lukasz doesnt have a way to test server side reports
Myself i have no way to test them in linux as i didnt run a linux for more than 15 Years now.

Please try and see what is working there. 
i guess export to pdf / excel / word will have some challenges there

**Comment by g136660** [comment]
Export working good in linux.
I need a viewer that matches the printed on paper.
Genuine Pdf not working. But working with workaround via converters from html to pdf.
But html making pagebreaks incorrect. Can sometimes rip his head off the table.
But it's better than nothing.
