### ISSUE TITLE
Fail loading images and tables on HTML5 rendering

### ISSUE THREAD

**Issue by medeiroshudson** [lkosson/reportviewercore#44]
for first, i have to congratulate all the team for hard work. it's a really aweseome lib!

i'm trying to rendering a remote SSRS report on my MVC (.NET 5), but it does not render properly images.

How it render on my MVC: https://i.imgur.com/WkqB4vv.png
How it should render (SSRS): https://i.imgur.com/uilmeXO.png 

Anything i doing wrong maybe?

**Comment by lkosson** [comment]
Charts indeed weren't rendered correctly in HTML. I have fixed it - now they should be embedded like static images instead of pointing to reportserver URL.
