### ISSUE TITLE
Images with Source=External fails

### ISSUE THREAD

**Issue by mpirritano** [lkosson/reportviewercore#45]
If you add an image, and set the "source" property to external and reference a file path - it fails with the following error:

An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null. (Parameter 'encoder')
System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)

LocalProcessingException: An error occurred during local report processing.
Microsoft.Reporting.NETCore.LocalReport.InternalRender(string format, bool allowInternalRenderers, string deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, out Warning[] warnings)

**Comment by mpirritano** [comment]
I noticed that urls to images seem to work, but physical file paths throw the error.

Thanks

**Comment by lkosson** [comment]
You should use `file://`-style URL for local files. Apart from that, there was an error in rendering placeholder image in PDF; I've just fixed it.
