### ISSUE TITLE
Bug - DateTime Parameters for the report in WinForms ReportViewer

### ISSUE THREAD

**Issue by CorsairRO** [lkosson/reportviewercore#46]
Hello,

i think i just found a bug in WinForms ReportViewer that applies to date parameters.
I think it applies to both server reports and local reports but i am not sure about local as i dont have any.

Selecting a date from Calendar to 01-May -> sets it first time, then it refreshes the parameters panel by itself and it is changed to 05-Jan
Sometimes it doesnt do that, but, if i set first time to a value and it is set correctly, second time i set the same parameter ( OR ANY other parameter in the parameters panel ) does the same shit.

So a consistent way to reproduce it if it doesnt happen first time is either try to set again still to a value with a day < 12 or to set some other parameter it doesnt matter which. Then it flickers the parameters, and the values in the dates becomes wrong

It seems that it just reparses the date this time with MM/DD format.

My report DOES NOT have any culture set, and my apps also uses the default. SO it cannot be from localization.
If it would be from localization i would get an exception setting the date to 31-May for example, but i dont get any errors, and the report works as it should with day > 12. All days < 12 do this crap.

Like i said what i notice is that the parameters panel flickers a bit and it puts me the wrong value in there, even if when coming from calendar selection it sets correct the date in the text.

thank you in advance for your answers there.
I can look by myself also in there, but i dont really know where to start to look in.

**Comment by lkosson** [comment]
Hi.

I can't really reproduce same behavior on default settings. On my sample server-side report, date parameter is displayed as 2021-05-01, which parses back correctly - but that's default short date format on my OS. When I changed it manually using `System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern = "MM-dd";` before displaying ReportViewer, it indeed alternates between `01-05` and `05-01` when opening calendar.

Please try setting `ShortDatePattern` for your application - at least for the duration of displaying ReportViewer. You might also fork the project and modify `Microsoft.Reporting.WinForms.DateControl.SetTextBoxValue` method to explicitly use other date format. In original ReportViewer it uses `ToShortDateString()` and `ToString()` which renders date using current culture settings. `Microsoft.ReportingServices.Common.DateTimeUtil.TryParseDateTime` method then tries to parse it using **any** available format using `GetAllDateTimePatterns` and gets bogus results.
