### ISSUE TITLE
Subreport and Memory Issues

### ISSUE THREAD

**Issue by corykroll** [lkosson/reportviewercore#47]
I recently moved to using this library for RDLC when moving from NET Framework to NET 5.  In doing so, a memory leak issue has come back up that I need to address.

I had a piece of code that got around a memory leak issue when running lots of reports in a short period of time in NET Framework.  It was:

LifetimeServices.LeaseTime = TimeSpan.FromSeconds(5);
LifetimeServices.LeaseManagerPollTime = TimeSpan.FromSeconds(5);
LifetimeServices.RenewOnCallTime = TimeSpan.FromSeconds(1);
LifetimeServices.SponsorshipTimeout = TimeSpan.FromSeconds(5);

The fix worked as a result of this thread:
https://www.codeproject.com/questions/636950/how-to-fix-memory-leak-in-microsoft-report-rdlc

I can't take this approach anymore  in NET 5, and was wondering how you are using remoting (or not) in this implementation and how one might do the same approach.

I realize this is somewhat of a vague request/issue, but could absolutely use the help should anyone in this project be able to address it.

**Comment by lkosson** [comment]
.NET Core (and .NET 5) don't support AppDomains anymore. In this library I have replaced them with `AssemblyLoadContext` which allows you to unload assemblies, including ones created on the fly for each subreport. Cross-context calls don't require remoting, so there is no need for leasing and object lifetime management either.

As far as I can tell, assembly is unloaded and it's memory freed within a second or less, at next full GC. At the unload time there is a debug output message - observe those as you run your reports in tight loop.
