### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'projectPath\file:\outputPath\Microsoft.ReportViewer.Common.dll'.

### ISSUE THREAD

**Issue by PentaTech** [lkosson/reportviewercore#48]
Hello,

I have some rdlc reports that import the `System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` assembly to be able to have some custom code on an image field.

Apparently when the assembly is getting imported this exception is thrown:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'projectPath\file:\outputPath\Microsoft.ReportViewer.Common.dll'. The filename, directory name, or volume label syntax is incorrect.`
in
`Microsoft.ReportViewer.Common/Microsoft.ReportingServices.Diagnostics/AssemblyLocationResolver.cs`
method
`public static AssemblyLocationResolver CreateResolver(AppDomain tempAppDomain)`
line 17
`return (AssemblyLocationResolver)tempAppDomain.CreateInstanceFromAndUnwrap(typeFromHandle.Assembly.CodeBase, typeFromHandle.FullName);`

Is there a workaround or is there no support for importing additional assemblies into reports?

Thank you in advance.

**Comment by lkosson** [comment]
I have fixed an error preventing external assembly loading. It should be now possible to execute such report.

Please keep in mind that reports are compiled in .NET Core context, so you can only load assemblies you could load in a typical .NET Core application. That means .NET Framework assemblies such as `System.Drawing, Version 2.0.0.0` are not available. You should either update a reference in your RDLC to use .NET Core assemblies/packages or move your custom logic from RDLC to your application and pass generated image as a parameter.
