### ISSUE TITLE
Generation fails when run through a single-file .exe

### ISSUE THREAD

**Issue by aaronhudon** [lkosson/reportviewercore#49]
Very strange behavior observed.  When running the project as an single .exe in .NET 5.0, an exception occurs when rending the report.

```
Microsoft.Reporting.NETCore.LocalProcessingException: An error occurred during local report processing.
 ---> Microsoft.Reporting.DefinitionInvalidException: The definition of the report '' is invalid. ---> Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: An unexpected error occurred in Report Processing. ---> System.TypeInitializationException: The type initializer for 'Microsoft.ReportingServices.ReportIntermediateFormat.Persistence.IntermediateFormatVersion' threw an exception. ---> System.ArgumentException: The path is empty. (Parameter 'path')
   --- End of inner exception stack trace ---
   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()
   at Microsoft.Reporting.NETCore.LocalReport.SetParameters(IEnumerable`1 parameters)
```

**Comment by lkosson** [comment]
In single-exe deployment there are no .NET assemblies available at runtime. This means it is not possible for Roslyn to reference them and compile report expressions to executable format.

For now I don't see any meaningful workaround. Perhaps it could be possible to replace Roslyn with some sort of runtime expression interpreter, but that would break more complex reports anyway.

**Comment by aaronhudon** [comment]
@lkosson thx for reply.  too bad, i didn't think single-exe introduced such complexity.
