### ISSUE TITLE
Having issues with using custom font on Windows

### ISSUE THREAD

**Issue by rsaa** [lkosson/reportviewercore#50]
We have a report that generates box labels with barcodes. The report uses the custom font "Code128Double.ttf" for bar codes. The .NET framework version works ok but the .NET Core version with ReportViewerCore control prints an error in the bar code. Can you please help?

![image](https://user-images.githubusercontent.com/1728603/120935505-253ab100-c6d1-11eb-8b97-a12ec8d8d2d2.png)

![image](https://user-images.githubusercontent.com/1728603/120936110-29b49900-c6d4-11eb-979b-bac902a0e238.png)

**Comment by lkosson** [comment]
Missing or invalid font shouldn't cause "#Error" output in the report. Please check if the field expression and format is set correctly and try re-adding the barcode to your report by starting with simple TextBox and setting one property at a time.
