### ISSUE TITLE
An error occurred during local report processing

### ISSUE THREAD

**Issue by bdshanto** [lkosson/reportviewercore#52]
I am using this library from report viewing to my .Net Core project, but I am facing a problem after completing production. 
In debugging mode, everything is 
working fine . But the fact in IIS. In IIS a got this error. ![image](https://user-images.githubusercontent.com/27566117/122665563-c180af80-d1c9-11eb-985e-d796c975bc0a.png)

**Comment by lkosson** [comment]
Please provide a full stack trace of the exception thrown during report processing.

**Comment by bdshanto** [comment]
Actually, this error throw after production, Inside IIS,

**Comment by lkosson** [comment]
Whenever the exception is thrown - without full details, including a stack trace, I can't really help.
