### ISSUE TITLE
Null refrence exception when a image is not found (Word export)

### ISSUE THREAD

**Issue by DadvDadv** [lkosson/reportviewercore#53]
When I put an external image in a report with href is a field of a dataset, if the url is not found (404) i've got an null reference exception on "InvalidImage" Ressource.

namespace : Microsoft.ReportingServices.Rendering.WordRenderer 
class : PictureDescriptor
in constructor  line 160, bitmap is null.

https://github.com/lkosson/reportviewercore/blob/5ce75f4e012ed27936350bd9a05bd140551b1506/Microsoft.ReportViewer.Common/Microsoft.ReportingServices.Rendering.WordRenderer/PictureDescriptor.cs#L160

**Comment by lkosson** [comment]
`ResourceManager` doesn't seem to work correctly when `System.Drawing` assembly isn't already loaded. I have embedded `InvalidImage` manually as base64 bitstream instead of using .resx. All renderers should now correctly handle missing images.

**Comment by DadvDadv** [comment]
Thx, I'll try it out, did you update the nuget package too ?

**Comment by lkosson** [comment]
I have uploaded nuget packages - they should be now available.
