### ISSUE TITLE
Integration test failed with an error TypeLoadException: Method "FilterDiagnostic" in type... 

### ISSUE THREAD

**Issue by zoran123456** [lkosson/reportviewercore#54]
![error](https://user-images.githubusercontent.com/11984207/125468176-567ad81d-ba90-4083-8dd4-768d66ed5202.png)

The library works well when running through the WebApi controller (using LocalReport).
However, when I tried to do integration tests using WebHostBuilder and TestServer it failed with an error in the attachment.

Any help would be highly appreciated. Thank you.

**Comment by lkosson** [comment]
It looks like a broken dependency of a Roslyn compiler. Please check if you are referencing same version of Microsoft.CodeAnalysis.Common and Microsoft.CodeAnalysis.VisualBasic packages and/or try explicitly selecting version 3.6.0 for both of them in your project.

**Comment by zoran123456** [comment]
Thank you very much @lkosson for the prompt reply. It was really about explicitly set dependency on CodeAnalysis.Common for one of the referenced projects. After it was fixed the issue was not there.

Your library works great! You are a life saver.


Kind regards,
