### ISSUE TITLE
System.NotSupportedException: 'Stream does not support seeking.'

### ISSUE THREAD

**Issue by corykroll** [lkosson/reportviewercore#55]
When calling Microsoft.Reporting.WinForms.ReportViewer method of RefreshReport, I get the error

```
System.NotSupportedException: Stream does not support seeking.
   at System.IO.BufferedStream.EnsureCanSeek()
```

The error being thrown is in line 963 of the method 

`internal override void CacheNonSharedProperties(PageContext pageContext) `

in 

`Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox`

The error is in the line:

`m_nonSharedOffset = propertyCacheWriter.BaseStream.Position;`

Here is the start of the method:

```
		internal override void CacheNonSharedProperties(PageContext pageContext)
		{
			if (!pageContext.CacheNonSharedProps)
			{
				return;
			}
			base.CacheNonSharedProperties(pageContext);
			BinaryWriter propertyCacheWriter = pageContext.PropertyCacheWriter;
			if (pageContext.PropertyCacheState != 0)
			{
				m_nonSharedOffset = propertyCacheWriter.BaseStream.Position;
			}
```

After this error, this gets thrown:

```
Microsoft.ReportingServices.OnDemandReportRendering.ReportRenderingException
  HResult=0x80131500
  Message=An error occurred during rendering of the report.
  Source=Microsoft.ReportViewer.Common
  StackTrace:
   at Microsoft.ReportingServices.Rendering.ImageRenderer.RendererBase.Render(Report report, NameValueCollection reportServerParameters, NameValueCollection deviceInfo, NameValueCollection clientCapabilities, Hashtable& renderProperties, CreateAndRegisterStream createAndRegisterStream) in C:\Users\Cory\Source\Repos\reportviewercore\Microsoft.ReportViewer.Common\Microsoft.ReportingServices.Rendering.ImageRenderer\RendererBase.cs:line 62

  This exception was originally thrown at this call stack:
    System.IO.BufferedStream.EnsureCanSeek()
    System.IO.BufferedStream.Position.get()
    Microsoft.ReportingServices.Rendering.HPBProcessing.TextBox.CacheNonSharedProperties(Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext) in TextBox.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.Create(Microsoft.ReportingServices.OnDemandReportRendering.ReportItem, bool, bool, Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext) in PageItem.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.Create(Microsoft.ReportingServices.OnDemandReportRendering.ReportItem, bool, Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext) in PageItem.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.CreateChildren(Microsoft.ReportingServices.OnDemandReportRendering.ReportItemCollection, Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext) in PageItemContainer.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.ReportBody.CreateChildren(Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext) in ReportBody.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItemContainer.DetermineVerticalSize(Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext, double, double, System.Collections.Generic.List<Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem>, ref bool, bool) in PageItemContainer.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext, double, double, Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem[], System.Collections.Generic.List<Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem>, ref bool, bool, double?) in PageItem.cs
    Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem.CalculateVertical(Microsoft.ReportingServices.Rendering.HPBProcessing.PageContext, double, double, Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem[], System.Collections.Generic.List<Microsoft.ReportingServices.Rendering.HPBProcessing.PageItem>, ref bool, bool) in PageItem.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
NotSupportedException: Stream does not support seeking.

```

Some odd things about this issue:
- It doesn't happen on every report I run - most render just fine - so I suspect it is data and/or report specific
- The specific report I am trying to run will always give me this error if it is the first time I run this report after starting my application - however - if I run other reports first, and then run this one, it works fine.  So it does seem like maybe the issue has something to do with the first time certain parts of the report viewer are loaded (maybe)?
- I am doing a lot of sending images as strings which makes the underlying data set rather large.  This might be around some kind of initial limitation to how big the data set can be on the first report rendered?

I'd appreciate any hints, or even a way to capture this error and then continue on.  Currently when this happens the program locks.  The application doesn't fade out or become unresponsive, but I'm locked and can't continue.

The lock is happening on the WaitOne() call in method 

`private void WaitForNextPage()`

in file Microsoft.Reporting.WinForms\FileManager.cs.  Here is the method:

```
		private void WaitForNextPage()
		{
			lock (m_lockObject)
			{
				if (m_status == FileManagerStatus.InProgress)
				{
					m_waitingForNextPage.Reset();
				}
			}
			m_waitingForNextPage.WaitOne();
		}
```

**Comment by lkosson** [comment]
Can you reproduce this error while application is running in debugger? If so, break when `System.NotSupportedException` is thrown and inspect `BufferedStream`'s `_stream` field (should be visible in non-public members). It should be either `MemoryStream` or `IsolatedStorageFileStream`, both of which support seeking during normal operation. Check if it disposed (inspecting its properties like `Position` or `Length` should throw `InvalidOperationException` and `CanSeek` should be `false`). If so, try setting a method breakpoint on their `Dispose` method to check what causes premature closure.

There are no inherent limits to size of dataset, but `IsolatedStorageFileStream` uses temporary disk storage (in C:\Users\...\AppData\Local\IsolatedStorage) that might be subject to some quotas and is limited by disk size obviously.

From what I can see, `FileManager`, `HPBProcessing` and other Stream-related functions are usually not used `RefreshReport`. Are you perhaps using `SetDisplayMode` to set `DisplayMode.PrintLayout` before report loads? If so, check if removing this call changes anything for this report.

**Comment by corykroll** [comment]
Wow - so I was indeed changing to `DisplayMode.PrintLayout` right away, and removing that line of code brought the rendered report up immediately without any issues (pretty fast, in fact).  Additionally, after seeing it and clicking the print layout button, it displayed in that mode just fine.
Any idea why this is?

I'll inspect the debugger shortly and reply with more info here in a bit.

**Comment by corykroll** [comment]
I'm not seeing `BufferedStream` that I can look at, but based on the error, I do see a `propertyCacheWriter.BaseStream`.  I'm hoping that is what you meant to analyze (if not, where can I find the `BufferedStream`?)

`BaseStream` has a `_stream` property that is of type `IsolatedStorageFileStream` which is Disposed based on the fact that both `Position` and `Length` upon analysis have a red X with System.ObjectDisposedExpception.  `CanSeek` is also `false`.

This is where I'm a bit confused though - I'm not sure how to capture the Disposed method to determine the premature closing.  Any tips on how I can wire something like this up for analysis in the debugger?

**Comment by lkosson** [comment]
Right - I meant inspecting `propertyCacheWriter.BaseStream`, which should be of type `BufferedStream`, which has `_stream` field containing underlying `IsolatedStorageFileStream`.

To see where it is disposed, add a new Function Breakpoint (CTRL-K, B), type name `System.Private.CoreLib.dll!System.IO.FileStream.Dispose` and select "All Languages", but that shouldn't be needed, as I have found most likely cause of the problem. It's quite hard to tell for sure without reproducing the problem, but most likely there is a race condition between report rendering (which happens on a separate thread in WinForms Report Viewer) and main UI thread calling `RefreshReport` in `OnLoad`. Rendering thread keeps requesting streams from `FileManager` and at the same time main thread calls `RefreshReport` which calls `FileManager.Clean` which disposes all already handed out streams.

In original ReportViewer, `RefreshReport` aborts any rendering threads. In .NET Core there is no `Thread.Abort()` method. As reported in issue #31, there are two workarounds - either patinently wait for rendering thread to complete its job and then continue with report refresh, or let the thread run in background. First one causes significant delays when loading and closing ReportViewer, second causes race condition. I think I'll have to take a second look at cooperative rendering cancellation.

For a workaround, try not setting `PrintLayout` in `OnLoad` method. It causes rendering thread to use `HPBProcessing`, which requests a lot of streams, which increase risk of disposing stream still in use. When rendering preview in normal layout, no streams are created.

**Comment by lkosson** [comment]
You can also call `SetDisplayMode` before actually loading your report definition. It causes `NullReferenceException` but it gets swallowed, and background rendering starts for the first time at `RefreshReport`, so there should be no race condition with cancellation and your report should load in Print Layout from the start.

**Comment by lkosson** [comment]
I have added some minimal cooperative thread abort support - just enough to handle reports initially loaded in `PrintLayout`.

**Comment by corykroll** [comment]
I'm running into some issues with first time report running after taking this update.
I'll run the report for the first time and the application sticks - but not on the main UI thread, as it doesn't grey out and Windows doesn't crash.

If I pause the debugger the line of code is in VBExpressionCodeProvider.cs
Line 46
var result = roslynCompilation.Emit(roslynAssembly);

This is being triggered when I call my line of code:
`reportViewer.LocalReport.SetParameters(reportParameters);`

**Comment by lkosson** [comment]
Is your report particularly big to explain such long compilation time? Can you post a full stack trace where the thread locks up inside `roslynCompilation.Emit` call?

**Comment by corykroll** [comment]
Sorry for my delay.  It does seem to work on smaller reports - I don't think that these reports that freeze up are particularly big however (no report takes more than 5-10 seconds tops to fully generate and display).  The unique thing I do a bunch of is generate images dynamically for records in a lot of my reports.  This creates datasets with fields that are byte[] arrays that get shows as images in the report.
Anyways I will takes latest version of the branch and work off of that.

I would be happy to get you a stack trace from a paused state... my apologies but could you guide me on exactly how to do that?
