### ISSUE TITLE
Repeat row header / columns  header on each page property does not work

### ISSUE THREAD

**Issue by avikunnure** [lkosson/reportviewercore#58]
Repeat row header / columns  header on each page property does not work

on tablix Properties - general tab option checkbox available repeat row header on each page which are not working currently

Thanks

**Comment by lkosson** [comment]
The feature seems to work fine. Please check your RDLC file in the original (.NET Framework-based) ReportViewer to see if header repeats.

**Comment by avikunnure** [comment]
but in html  report columns header are not working .
Thanks
