### ISSUE TITLE
Loads System.Data.SqlClient.dll, even though no use case of SQL in my project.

### ISSUE THREAD

**Issue by RajeshAKumar** [lkosson/reportviewercore#61]
I tested and it worked fine with .NET 6.0 and VS 2022 Preview version.

However, the runtime is referencing the System.Data.SqlClient.dll even though my project does not use it.
If I delete the referenced dll, the report rendering fails for LocalReport, after calling RefreshReport API.

**Comment by RajeshAKumar** [comment]
I have fixed this and have a pull request for this.
Ikosson, please review and merge.

**Comment by lkosson** [comment]
Hello. I have merged your pull request.

**Comment by RajeshAKumar** [comment]
Thank you Ikosson.

Do you know if you will be able to compile the source against .NET 6.
The reporting process is slow and can really take advantage of all the .NET 6 performance improvements.

**Comment by lkosson** [comment]
Compiling the project using .NET 6 SDK definitely should be possible, but it wouldn't change the performance by any noticable amount. All the optimisations done by CoreCLR team in .NET 6 apply to every loaded assembly, no matter which SDK version has been used to compile it.

I try to keep this project as close to the original Microsoft sources as possible, but if there are some performance regressions, I'll do my best to fix them if possible.

**Comment by RajeshAKumar** [comment]
Thank you Lukasz.

I tried to compile and fixed 3 minor ambiguous references and created pull
requests.
I would also like to keep the sources as close as possible to MS code.

However, the ability to compile to .NET 6 might be important for us to fix
any future issues.
We are migrating all of our product code to .NET 6 and this
ReportViewerCore you have created is a tremendous help to us, instead of
migrating all of our reporting to a new technology.

Thanks a lot for your efforts.

**Comment by lkosson** [comment]
Your PRs are between your repositories, not between yours and mine. I have made new ones and merged your changes.

**Comment by RajeshAKumar** [comment]
Thank you.

Sorry I didnot realize the changes weren't on the main repository.
I am doing this the first time and will be careful in future.
