### ISSUE TITLE
How add datasource in Microsoft.NET.Sdk ?

### ISSUE THREAD

**Issue by torgashov** [lkosson/reportviewercore#68]
Hello! 
I have project with type Microsoft.NET.Sdk.
Even after installing the rdlc report designer extension, new dataset wizard fails to show classes from your project and .NET Core projects don't have .datasource file support either. 
Can you explain how to use the workaround is to create and add .xsd file to your project with definitions of types you want to use in your reports?
I can not understand.
Thank you!

**Comment by lkosson** [comment]
Copy the code snippet from a readme file to a new class/method in your project and initialize `types` array with the types you would like to use in a report. Run the method (as a console application or by any other means - it doesn't matter). You should get a `ReportItemSchemas.xsd` file. Copy it to your project's source directory. Now when you open a designer for any RDLC file in your project, in `Add Dataset` you'll see a `ReportItemSchemas` datasource with all of the types you have specified listed as datasets.

Whenever your report object changes or you want to add another report, repeat the same process to refresh your `.xsd` file.

**Comment by torgashov** [comment]
Thank you very much. It works now.
