### ISSUE TITLE
Error Setting Parameters

### ISSUE THREAD

**Issue by twalbers** [lkosson/reportviewercore#69]
I am attempting to get this working with .netCore 5 using an API Controller but am having issues setting the report parameters.
  | StackTrace | "   at Microsoft.Reporting.NETCore.LocalReport.EnsureExecutionSession()\r\n   at Microsoft.Reporting.NETCore.LocalReport.SetParameters(IEnumerable`1 parameters)\r\n   at Calcutta.Controllers.ReportController.<GetResults>d__4.MoveNext() in D:\\GitHub\\Calcutta\\Calcutta\\Controllers\\ReportController.cs:line 185" | string

From what I can tell it is saying the the report definition is invalid but I know the report works.  

I was unable to install Microsoft.CodeAnalysis.Common v 3.6.0.  The lowest I was able to install was 3.8.0 due to other nuget packages

Any help is appreciated.

**Comment by lkosson** [comment]
Please include full details and stack trace of the thrown exception.

You can try directly referencing newer version of `Microsoft.CodeAnalysis.VisualBasic` in your project. It depends on exact same version of `Microsoft.CodeAnalysis.Common`, which should satisfy dependencies of your other packages.
