### ISSUE TITLE
Subreportprocessing timing issue.

### ISSUE THREAD

**Issue by Ingreydavid** [lkosson/reportviewercore#71]
I was getting an error (Data retrieval failed for the subreport) when using subreports. I was adding the datasource in the SubreportProcessing event but the routine

IEnumerable ControlSubReportInfoCallback(PreviewItemContext subReportContext, ParameterInfoCollection initialParameters)

was returning the subreportProcessingEventArgs.DataSources with a count of 0. I added a thread.sleep(500) just before the routine returns the subreportProcessingEventArgs.DataSources and the count was then 1.

This looks like a timing issue.

**Comment by lkosson** [comment]
Hi. `ControlSubReportInfoCallback` and `SubreportProcessing` should be thread-safe and invoked from a dedicated report processing thread. As far as I can tell, no other thread can intercept and/or change value of `subreportProcessingEventArgs.DataSources` and cause `ControlSubReportInfoCallback` to return something else.

Please check if you have exactly one `SubreportProcessing` event handler attached and it is not an `async void` method. Using `async void` could cause `ControlSubReportInfoCallback` to continue executing prematurely; before you actually set `e.DataSources`.

**Comment by Ingreydavid** [comment]
Thanks for the reply, you are correct the issue was an awaited async call within the event handler. I have refactored my code and all is now working correctly now.

 

Thanks for the help.
