### ISSUE TITLE
warning NU1608

### ISSUE THREAD

**Issue by biyori** [lkosson/reportviewercore#74]
Hello,

I'm using this in a .net 5 project after installing CodeAnalysis 3.8.0 I am getting a nuget warning:
```
warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.VisualBasic 3.6.0 requires Microsoft.CodeAnalysis.Common (= 3.6.0) but version Microsoft.CodeAnalysis.Common 3.8.0 was resolved.
```
I could suppress this warning but what can be done to remove  `CodeAnalysis` completely as a dependency?

**Comment by lkosson** [comment]
`CodeAnalysis` is required by `VisualBasic` which in turn is required to compile RDLC expressions. Unfortunately, `VisualBasic` requires exact version of `CodeAnalysis` and there is not much that can be done about this.

You can try to add explicit reference to `VisualBasic` version 3.8.0 in your project, which should also force version 3.8.0 of `CodeAnalysis` which you already use.

**Comment by lkosson** [comment]
Nuget packages now target separately .NET 3.1, 5 and 6, so there should no longer be conflicts between `Microsoft.CodeAnalysis.*` packages versions.
