### ISSUE TITLE
HTTP Error 500.31 - Failed to load ASP.NET Core runtime

### ISSUE THREAD

**Issue by Naweap** [lkosson/reportviewercore#77]
Hello,

I'm working on a .NET 5.0 application. I added the package via the Nuget Package Manager from Visual Studio.

Just after the package was added, I got the following error from the IIS Express web server :

**_HTTP Error 500.31 - Failed to load ASP.NET Core runtime_**

Do you have any idea about where the issue could come from ?

Note that the application was running fine before and I got all the required .NET runtimes installed.

Thanks in advance

After a bit of investigation, I've notice the source of this issue :

```
Error:
  An assembly specified in the application dependencies manifest (xxx.deps.json) has already been found but with a different file extension:
    package: 'ReportViewerCore.NETCore', version: '15.1.15'
    path: 'lib/netcoreapp3.1/Microsoft.ReportViewer.ProcessingObjectModel.dll'
    previously found assembly: 'xxx\bin\Debug\net5.0\Microsoft.ReportViewer.ProcessingObjectModel.DLL'

```
It seems like there is a duplicate load of the same DLL but with a different extension.

My solution contains :

1. An ASP.NET MVC with .NET 5 project which is the main entry of the application.
2. A .NET 5 project responsible for the generation of the reports.
3. A .NET 5 report project containing the reports rdlc files.

The dependencies within theses projects are in the order above.

Currently I got no idea why I'm getting this error. I cannot find any similar package or something that could make this duplication of DLL.

Any help is much appreciated.

Edit : update and spelling

**Comment by lkosson** [comment]
The `ReportViewerCore.Sample.AspNetCore` project in this repo seems to work fine with .NET 5, so I guess it's not an issue with the package by itself.

By the looks of the error, it seems you have somehow referenced `Microsoft.ReportViewer.ProcessingObjectModel.DLL` twice in your project - as a `ReportViewerCore.NETCore` nuget package and by explicitly specifying the assembly or from another package. Please review your project's references and check if you haven't by accident also referenced `Microsoft.ReportViewer.WinForms` nuget package (which also provides `Microsoft.ReportViewer.ProcessingObjectModel.DLL`).

**Comment by Naweap** [comment]
First, thanks for you quick reply.

By looking at the _xxx.deps.json_ file ( `An assembly specified in the application dependencies manifest (xxx.deps.json) has already been found but with a different file extension`), `Microsoft.ReportViewer.ProcessingObjectModel.DLL` assembly is imported from the following sources :

- `ReportViewerCore.NETCore/15.1.15`
- `Microsoft.Report.Viewer/11.0.0`

I tried to look for that package (`Microsoft.Report.Viewer`) which I didn't found. I also looked for an assembly imported manually, didn't find anything for the moment.

**Comment by lkosson** [comment]
`Microsoft.Report.Viewer` looks like [this](https://www.nuget.org/packages/Microsoft.Report.Viewer/) nuget package. You should have it mentioned somewhere in `.deps.json` in `dependencies` section of either your application or some other package you are using.

**Comment by Naweap** [comment]
Alright, I found the source of that package. It comes from another package. Unfortunally I need this package too and cannot remove it. Do you know if there is a way to centralize this DLL dependency or a workaround to avoid this DLL conflict ?

**Comment by lkosson** [comment]
You can repackage either of those packages and edit the dependency out or even extract DLLs from `.nuget`s and reference them directly in your project. Other than that, I don't think there is a way to have .NET Core load multiple versions of the same assembly.

**Comment by Naweap** [comment]
Alright thanks for your reply and great support ! I will think about how to deal with that.
