### ISSUE TITLE
Error running on MacOS

### ISSUE THREAD

**Issue by chhinsras** [lkosson/reportviewercore#79]
`An unhandled exception occurred while processing the request.

PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
System.Drawing.LibraryResolver.EnsureRegistered()

TypeInitializationException: The type initializer for 'Gdip' threw an exception.
System.Drawing.SafeNativeMethods+Gdip.GdipCreateBitmapFromScan0(int width, int height, int stride, int format, IntPtr scan0, out IntPtr bitmap)

TypeInitializationException: The type initializer for 'Microsoft.ReportingServices.Rendering.ImageRenderer.Renderer' threw an exception.
Microsoft.ReportingServices.Rendering.ImageRenderer.Renderer..ctor(bool physicalPagination)

LocalProcessingException: An error occurred during local report processing.
Microsoft.Reporting.NETCore.LocalReport.InternalRender(string format, bool allowInternalRenderers, string deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, out Warning[] warnings)

`

**Comment by lkosson** [comment]
On non-windows platforms you can only use HTML4.0, HTML5, EXCELOPENXML and WORDOPENXML formats.

**Comment by chhinsras** [comment]
> On non-windows platforms you can only use HTML4.0, HTML5, EXCELOPENXML and WORDOPENXML formats.

@lkosson Thank you. do you happen to know how can I design RDLC if I am using mac M1

**Comment by lkosson** [comment]
No idea.

**Comment by chhinsras** [comment]
@lkosson been searching for awhile. but could not find the how to design RDLC report on MacOS yet.

**Comment by lkosson** [comment]
A few weeks ago Microsoft published [RDLC designer for VS2022](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftRdlcReportDesignerforVisualStudio2022). If that doesn't work on VS for Mac, I'd suggest running VS inside a Windows VM.

**Comment by chhinsras** [comment]
@lkosson . it must be the solution for now.  just struggling running Windows on M1 8GB
