### ISSUE TITLE
winforms .rdlc error client rendering on some report file (with colors) on project Dotnet5

### ISSUE THREAD

**Issue by chandra-arifin** [lkosson/reportviewercore#8]
i have alot of report viewer client (.rdlc) files.
after the patched u do yesterday, i can run the report viewer controls smoothly on my new dotnet5 winforms. thanks alot.
but after i refreshreport, error occured (not all rdlc files. but when the report contains COLORS).

`an error occurred during client rendering. the type initializer for 'microsoft.reporting.winforms.gdicontext' threw an exception. could not find the resource "microsoft.reporting.winforms.interactivityimages.resources" among the resources ... etc.` 

i attached the error message here:

![image](https://user-images.githubusercontent.com/39976579/99044548-80387980-25c2-11eb-94d5-1d26746119cf.png)

i can solved this problems by manually remove the ROWS and then manually type description and set COLORS. this problems goes away.

is it the limitation of the report viewer control on dotnet5? since the gdicontext is only support on windows, maybe. :p
any comment will be appreciated.

**Comment by lkosson** [comment]
InteractivityImages.resx got embedded with mangled name, not sure why. I have forced proper logical name in csproj, please checkout the newest version and see if it fixes your issue. If yes, I'll publish updated package.

**Comment by chandra-arifin** [comment]
still error. thanks for the reply.
i will try it again. will try to find the solution for this.

**Comment by chandra-arifin** [comment]
weird. i do the following works:
1. copy all Microsoft.ReportViewer.Common.dll, Microsoft.ReportViewer.DataVisualization.dll, Microsoft.ReportViewer.ProcessingObjectModel.dll, Microsoft.ReportViewer.WinForms.dll to my project
2. clean solution
3. build and run programs
4. still errors

BUT, when i do the following:
1. COPY ALL PROJECTS from your solutions (4 projects).
2. Clean solutions
3. Build and Run. the program WORKS.

so? whats make that happened? i already remove my dll and attach my dll again. but still error. but all project attached, it works.
Finally. i can say BIG THANKS to you.
i really appreciate your works on this ReportViewer on dotnet5.
and i think this solved my problem.
