### ISSUE TITLE
How to razorpage render html

### ISSUE THREAD

**Issue by rungsoso** [lkosson/reportviewercore#80]
Do you have an example of how to razorpage render html (reports from a remote SSRS server)

**Comment by lkosson** [comment]
Take a look at `ReportViewerCore.Sample.AspNetCore` and `ReportViewerCore.Sample.WinFormsServer` projects in this repo. Use `"HTML5"` output format.

**Comment by rungsoso** [comment]
> Take a look at `ReportViewerCore.Sample.AspNetCore` and `ReportViewerCore.Sample.WinFormsServer` projects in this repo. Use `"HTML5"` output format.

Thank you very much
