### ISSUE TITLE
 reportviewercore toolbar?

### ISSUE THREAD

**Issue by rungsoso** [lkosson/reportviewercore#81]
please help me i have 2 questions.

1. how to render html in razorpage without export html?

2. reportviewercore can there be a toolbar like a report viewer?

![1644477800924](https://user-images.githubusercontent.com/24908027/153358825-ee790200-e502-4cce-91d0-eb2c664b14b5.jpg)

**Comment by lkosson** [comment]
Interactive report viewer control is not available in this version. You can only render static HTML.

**Comment by rungsoso** [comment]
> Interactive report viewer control is not available in this version. You can only render static HTML.

thanks for reply.
