### ISSUE TITLE
Word Docx with images on linux

### ISSUE THREAD

**Issue by a-shawky** [lkosson/reportviewercore#83]
Hello,

I am trying to generate a report in docx format under linux container, the report contains images, but the output file has no images.

Is generating docx with images not supported on linux container?

Regards

**Comment by lkosson** [comment]
As far as I can tell - DOCX images renderer it should work just fine, as long as image files are available from inside of the container.

**Comment by a-shawky** [comment]
Hi @lkosson 

Is there a sample on binding with Images of linux and how to pass the images path to the report?

**Comment by lkosson** [comment]
There isn't, but it shouldn't be different from how images work in original ReportViewer - either use `EnableExternalImages` or pass image data as base64-encoded string.
