### ISSUE TITLE
Microsoft.Reporting.NETCore.ReportPreviewStrings.resx Not found

### ISSUE THREAD

**Issue by gonzalo42** [lkosson/reportviewercore#87]
Im currently having the following issue

Could not find the resource "Microsoft.Reporting.NETCore.ReportPreviewStrings.resx", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

This happens when I clear the data sources and try to add a new one. please help.

`// Get RDL file
            var path = Path.Combine(Directory.GetCurrentDirectory(), "Reports", "ProductionReport.rdl");

            // Open RDL File as a Stream
            var reportDefinition = new FileStream(path, FileMode.Open);

            // Load Report from RDL file
            var report = new LocalReport();
            report.LoadReportDefinition(reportDefinition);

            // Add Report DataSouce
            report.DataSources.Clear();
            report.DataSources.Add(new ReportDataSource("ProductionReportDataSource", ds));`

**Comment by lkosson** [comment]
I have added the missing resource just yesterday (#85). Until I publish updated nuget packages, to see what's the actual error in your case, inspect exception stack trace and look for line starting with `Microsoft.Reporting.NETCore.ReportPreviewStrings.get_XXX` and directly next one. Most likely your `ds` data source has a wrong type.

**Comment by gonzalo42** [comment]
Got it figured out. Thanks a bunch!
