### ISSUE TITLE
.Net 6.0 Web API -> System.Resources.MissingManifestResourceException: When loading a single object datasource instead of List

### ISSUE THREAD

**Issue by deepesh002** [lkosson/reportviewercore#92]
Hi,

We have multiple RDLC templates in our project that use a mix of single and list type of objects to load data sources for the various elements and subreports.

However, since we upgraded to use .Net 6.0 for our Web API, we are getting the following exception while loading

System.Resources.MissingManifestResourceException: 'Could not find the resource 
             "Microsoft.Reporting.NETCore.ReportPreviewStrings.resources" 
             among the resources "Microsoft.Reporting.CommonStrings.resources" embedded in the assembly 
             "Microsoft.ReportViewer.NETCore", 
             nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.'

Attached here is a sample .Net 6.0 Web API project . 

We are using the latest version :- 15.1.16

Please advise on a fix for this as loading as a list instead of an object fails the bindings on our template rdlc files
[RdlcTest_ObjectDataSource_NotWorking_Sample.zip](https://github.com/lkosson/reportviewercore/files/8703115/RdlcTest_ObjectDataSource_NotWorking_Sample.zip)

Hit the end point while debugging like this -> https://localhost:7191/api/rdlc

**Comment by lkosson** [comment]
ReportViewer (both original and from this repo) don't support binding to a standalone object. You should put your object in a list or array and pass it in this form as a datasource.

As for the actual exception - it is caused by a misplaced resource when trying to construct an error message telling that you need to use IEnumerable. I'll fix that in the upcoming release.

**Comment by lkosson** [comment]
Updated nuget package, version 15.1.17, is now available.
