### ISSUE TITLE
XPS format support

### ISSUE THREAD

**Issue by ryanryanorient** [lkosson/reportviewercore#93]
Is it possible to support xps output?
xps output can be printed directly on the client,
pdf also needs an extra renderer which is not a good idea

**Comment by lkosson** [comment]
Directly from RV - not really. The best you can do is to print your report to Microsoft XPS Document Writer virtual printer.

**Comment by ryanryanorient** [comment]
> 
Thanks, usually we generate reports on the server side, in the client rendering, I don't want to use the Reportview component on the client side, because it has a lot of limitations, I want to use a generic scheme, try to avoid platform dependencies, I thought of EMF, unfortunately, WPF does not support EMF rendering, Microsoft's reason is that EMF has security issues
