### ISSUE TITLE
Different output format position on render to PDF and render to DOCX

### ISSUE THREAD

**Issue by agunghanifan** [lkosson/reportviewercore#94]
Hello,
I am using .NET 6, ReportViewerCore.NETCore version 15.1.16 and trying to make Docx format look like a Pdf format. What am I supposed to do?

this is an example I just try using `report.Render("WORDOPENXML", null, out mimeType, out encoding, out fileNameExtension, out streamIds, out warnings);` for docx format and create file with the byte array to Docx file with `File.WriteAllBytes();`. For pdf format, i am using `report.Render("PDF", null, out mimeType, out encoding, out fileNameExtension, out streamIds, out warnings);` and creating a file with the byte array to a Pdf file with `File.WriteAllBytes();` too.

DOCX format
![image](https://user-images.githubusercontent.com/71800684/174577298-54cdc88d-68da-40ec-a5e4-81189a44a6b6.png)

PDF format
![image](https://user-images.githubusercontent.com/71800684/174577390-06ec5d29-a027-479b-82c3-a76ae330ec10.png)

You can see the different positioning in the picture above.
Thanks in advance.

**Comment by agunghanifan** [comment]
Sorry for late response, thank you for your response.
I can't using the original packages because I'm currently using .NET 6 and when I am force to use .net framework, some error appear and this is not the point of my problem, is there anything else I need to do? some settings or something in my code?
Thanks in advance.

**Comment by lkosson** [comment]
Create a new .NET Framework project, add original RV references, plug in your report with some minimal dataset and see if the layout still changes between PDF and DOCX.
