### ISSUE TITLE
ServerReport - DisplayName not working

### ISSUE THREAD

**Issue by rasika-sinha** [lkosson/reportviewercore#95]
Hello,

I am using the ServerReport of Microsoft.Reporting.NETCore. I am using it in a dot net core 6.0 WebAPI project, returning the file stream so it opens the report in pdf format on the browser.
I wanted to set the DisplayName of the server report so that when a user downloads it from the browser a proper name is prepopulated and not the endpoint's name.
I have set the serverReport.DisplayName property but it is not reflecting. Can you please let me know how will this work?

Thanks!

**Comment by lkosson** [comment]
I see. Not sure what to do with this. `DisplayName` doesn't really seem to be used - neither in this project nor in original sources.
