### ISSUE TITLE
Localization through CurrentUICulture doesn't work

### ISSUE THREAD

**Issue by jeremyc87** [lkosson/reportviewercore#97]
Hello,

I have checked how to change the localization of the original ReportViewer and it is said that the control check for the current Culture. Apparently, this is not working with this control. Is it possible to implement that?
Or is it me who did something wrong?

Thanks.
Best regards.

**Comment by lkosson** [comment]
Please provide a project reproducing the expected behavior using original RV.

**Comment by jeremyc87** [comment]
Hi,

Here is a project reproducing the behaviour. It does work only with language installed from this link:
https://www.microsoft.com/en-US/download/details.aspx?id=35747

And here is the test project :

[DemoRVLoc.zip](https://github.com/lkosson/reportviewercore/files/9178788/DemoRVLoc.zip)

**Comment by lkosson** [comment]
I see. Satellite assemblies with localized strings are indeed missing from this project.

**Comment by lkosson** [comment]
I have added missing localized strings for WinForms RV control. You can expect new NuGet package in a few days.
