### ISSUE TITLE
Datasource Wizard is weird and I can't make it work

### ISSUE THREAD

**Issue by jeremyc87** [lkosson/reportviewercore#98]
Hi,

I am working with .NET 6. Originally, I am working in a "big" project. The project with ReportViewer in it is in C# WPF .NET6 in Visual Studio 2022. When I create a report, no problem. When I try to add a datasource from an object, I am unable to see any of my class in the project.

I have tried in a brand new solution still in .NET6. Created a new project called TestRV1 in C# WPF. Cretaed a basic class, created a report. And still not able to see any class from my own project. I DO have generated the project before, several time, without error, I know it is required for the wizard the see the classes.
Then I have created a new project TestLib as C# class library. I have created a new basic class in it. Then I have referenced the new lib from the first project, and compiled solution. Now I am able to see the class from TestLib but when I select it and click next I have a MsgBox error with "Null reference object" stuff and nothing append. the dataset is not created...

I have tried several other stuff and here is my test solution for you to see:
[TestRV.zip](https://github.com/lkosson/reportviewercore/files/9178977/TestRV.zip)

I hope you can point me to the problem.

**Comment by lkosson** [comment]
Please see `Designing new reports` section in the readme of this repo. The workaroud is to generate `.xsd` file containing your types definitions.

**Comment by jeremyc87** [comment]
Thank you very much, it does work this way!!

**Comment by asine** [comment]
> Thank you very much, it does work this way!!

pls share the success demo solution.
