### ISSUE TITLE
Is it possible to get the report execution metrics like processing time /rendering time. 

### ISSUE THREAD

**Issue by najmbe** [lkosson/reportviewercore#99]

**Comment by lkosson** [comment]
Which functionality from the original Report Viewer are you refereing to?

**Comment by najmbe** [comment]
I was referring to  Microsoft.ReportingServices.OnDemandProcessing . I have used as a nuget package 15.1.16. able to process the existing RDL for a simple report with a single subreport. Now I wanted to get the time takes to execute the sub report , the rendering time . just like we have in SSRS.

**Comment by lkosson** [comment]
Nothing changed in that regard. All the metric-related classes (like `DataProcessingMetrics`) are still available and used in this project.

**Comment by najmbe** [comment]
Yes I see the class in the library. Let me explore on how to use it
